### ISSUE TITLE
How to do partial application?

### ISSUE THREAD

**Issue by dalgard** [selfrefactor/rambda#149]
I was surprised not to see `partial` in Rambda's docs – is there a different way to do partial application, or are you content with things like arrow functions?

Often, the `pipe` and `partial` functions are all I use in a functional library, but I quickly feel limited without them 🙂

**Comment by dalgard** [comment]
Now that I think of it – adding `partial` to Rambda would be a great opportunity to free it from its current ugliness of having to wrap the arguments in an array 🙌

**Comment by selfrefactor** [comment]
First, I thank you for the suggestion as it seems like a good one.

Just to clarify the specification:

```
const greet = (salutation, title, firstName, lastName) =>
  salutation + ', ' + title + ' ' + firstName + ' ' + lastName + '!';

const sayHello = R.partial(greet, 'Hello');
const sayHelloToMs = R.partial(sayHello, 'Ms.');
const canPassAnyNumberOfArguments = R.partial(greet,  'Hello', 'Ms.');
sayHelloToMs('Jane', 'Jones'); //=> 'Hello, Ms. Jane Jones!'
```

**Comment by dalgard** [comment]
Thank _you_ 😌 Yeah, it looks correct to me.

Maybe it's just me being weird, but it almost feels like the API of `partial` is incomplete as long as we can't defer its own first argument to final, "point free" position – I guess it's because that argument seems like the most important one.

Oh well, I'm likely just being ignorant about the trappings of `lift` or some other FP thing. And I was never too impressed by the `R.__` placholder overload. Too synthetic – like _syntactic aspartame_* 😉

(I'm coining that concept, of course, unless it already exists, in which case I'm burning it.

**Comment by selfrefactor** [comment]
I did publish a new version, that includes `R.partial` with the specification from above. The single note is that Typescript definition are left very basic(in the same way `R.curry`). This definition could be subject to improvement, but for now I'll leave it as it is.

**Comment by dalgard** [comment]
Thank you! 🙏
