### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by WhoAteDaCake** [selfrefactor/rambda#16]
I believe that we should use a linter, as then contributing to the repo would be easier and everyone would be using same coding conventions.

**Comment by selfrefactor** [comment]
Actually there is a linter configuration that I use. 
I will share the code and I will add `Contribute` section, which will include lint instructions.

**Comment by selfrefactor** [comment]
Closing the issue - lint instructions are added to `Contribute guidelines` section.
