### ISSUE TITLE
tools.d.ts lost from npm package

### ISSUE THREAD

**Issue by victordidenko** [selfrefactor/rambda#175]
Looks like file `tools.d.ts` is absent in NPM package...
```
$ tsc
node_modules/rambda/index.d.ts:1:22 - error TS6053: File '.../node_modules/rambda/tools.d.ts' not found.

1 /// <reference path="./tools.d.ts" />
                       ~~~~~~~~~~~~
```
I tried `yarn` and `npm` both

**Comment by selfrefactor** [comment]
Obviously it is not included in files declaration. Will fix it right away.

**Comment by victordidenko** [comment]
Sorry, I've never published my own packages on NPM yet, so it was not obvious for me 🤷‍♂️

**Comment by selfrefactor** [comment]
Learn something useless every day :)

Within 1 hour patch will be deployed.

**Comment by victordidenko** [comment]
Now there is no index.d.ts and no types at all 🙇
<img width="208" alt="Screenshot 2019-05-27 at 20 51 02" src="https://user-images.githubusercontent.com/15016227/58433792-66029700-80c1-11e9-844b-bf5dc8d3afff.png">

**Comment by selfrefactor** [comment]
my bad

**Comment by selfrefactor** [comment]
Should be fine now

**Comment by victordidenko** [comment]
All is good, thank you!
