### ISSUE TITLE
Using internal curry

### ISSUE THREAD

**Issue by WhoAteDaCake** [selfrefactor/rambda#18]
I've noticed that a lot of functions have a check whether the arguments are  defined inside of them. 
To cut down on size, wouldn't it be better to just wrap them in curry functions ?

**Comment by selfrefactor** [comment]
Spon on!
Marked as `enhancement` with the idea to be solved today or tomorrow

**Comment by WhoAteDaCake** [comment]
The only downside of this is that It will slow them down by a tiny margin.

**Comment by selfrefactor** [comment]
It seems it is not tiny, at least with the current implementation of `R.curry`

![rambda-benchmark](https://user-images.githubusercontent.com/2149294/28609756-933080b8-71ee-11e7-83f5-c73ecc38ff60.png)

**Comment by selfrefactor** [comment]
I am closing the issue now, as currently there isn't appropriate solution available.
