### ISSUE TITLE
Typing error after upgrading to latest version

### ISSUE THREAD

**Issue by kuchta** [selfrefactor/rambda#180]
Hi,

This code:
```javascript
type ErrorsGrouped = {
    [index: string]: {
        error: string;
    }[];
}
R.forEach((value, key) => console.log(\``${key}: ${value.length}``), errorsGroupped: ErrorsGrouped);
```
which was compiling fine at version 2.5 stopped working with upgrade to 2.11 with error:

`
Argument of type '(value: any, key: any) => void' is not assignable to parameter of type '(x: { error: string; }[]) => void'
`

The same with map.

Thanks for suggestions

**Comment by selfrefactor** [comment]
I just approved your PR and you can test it with version `2.11.1`. I will test if the issue is still present and if so, I will post some solution.

**Comment by kuchta** [comment]
Works with latest version. Closing the issue...
