### ISSUE TITLE
List of Ramda methods intentionally missing in Rambda

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#218]
For example `R.and(true, true);` is one such example. I really feel that seeing

```
const a = compose(
  and(head(list)),
  last
)(list)
```

would make a normal person mad.

The other case:

```
if(and(x,y)) fn()
```

is also confusing.

**Comment by ku8ar** [comment]
Yes, it's confusing. But the main motive of the Ramda developers is to create a library that allows programming in the point-free paradigm.

We in the team use it mainly to create Redux (Reselect) selectors:

```
// point-free
const isBoth = createSelector(
  hasA,
  hasB,
  and
)

// ugly old style
const isBoth = createSelector(
  hasA,
  hasB,
  (resultA, resultB) => resultA && resultB
)
```

I know, it's just a bit of code. And the example is not very sensible. But even such functions allow to reduce the number of chars in code.
Additionally, in the case of logic gates, in JS it is very easy to make a mistake and write `&` (bitwise) instead of `&&`. But when we have the `and` function, we will not make such bug.

**Comment by selfrefactor** [comment]
Good logic. I think I would go in direction to separate this `second-class` methods as they don't clutter the API. I see them in very separate API section in README and this way we can both be partially happy. Hope you are fine with that.

**Comment by ku8ar** [comment]
I think the whole "Logic" group could be separated. BTW you didn't think about a slight change GH Page? For example, adding a search engine? Ramda has nice "Filter" field on site...

**Comment by selfrefactor** [comment]
Changing the framework that build GH page is one thing that should be addressed. I though about that this is a good change to give `docusaurus` a chance. But before that being ready, we can meanwhile add a filter plugin if such exists for `docsify-cli`. I will open separate issue for this update.

**Comment by ku8ar** [comment]
I need to read about this docusaurus. But there is React, so it's probably OK ;)

**Comment by selfrefactor** [comment]
Ramda is introducing a `trimFix` method, which seems like something I prefer having in string-focused library.

**Comment by ku8ar** [comment]
heh. I don't see this func. Where it is?

BTW I am not working now on Rambda, because Im doing another project. But I think I will put some PRs at the end of this month ;)

**Comment by selfrefactor** [comment]
Hi @ku8ar 
Take your time, I am doing now typings tests with `dtslint now.

As for `R.trimFix` - I am following several repos with https://devhubapp.com/ including Ramda and I saw this method as a opened PR so it may land with the new versions of Ramda.
