### ISSUE TITLE
No index in R.reduce

### ISSUE THREAD

**Issue by kpchand** [selfrefactor/rambda#227]
There is no index in the callback function to R.reduce. Can this be added?

**Comment by selfrefactor** [comment]
This is the just of the method:

**Comment by kpchand** [comment]
![image](https://user-images.githubusercontent.com/1081675/62799283-06335e00-bafe-11e9-92eb-a33d41027605.png)

**Comment by selfrefactor** [comment]
Just publish it with `1.12.4`
