### ISSUE TITLE
add R.keys

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#23]
`R.keys({a: 1, b: 2, c: 3}); //=> ['a', 'b', 'c']`

**Comment by wind13** [comment]
Why I have not find the `R.keys` in the [document](https://selfrefactor.github.io/rambda)?

**Comment by selfrefactor** [comment]
Because it is not implemented. I am reopening the issue and the method will be in the next version. Give me one day for that.

**Comment by selfrefactor** [comment]
Added in the latest version.
