### ISSUE TITLE
R.Placeholder: R has not exported member Placeholder

### ISSUE THREAD

**Issue by tonivj5** [selfrefactor/rambda#234]
Hi! I have updated to `3.0.0` and there's a problem with typings, concretely into [tools.d.ts line 86](https://github.com/selfrefactor/rambda/blob/master/tools.d.ts#L86) and [tools.d.ts line 100](https://github.com/selfrefactor/rambda/blob/master/tools.d.ts#L100). I researched a little, the problem is that Placeholder was removed from [index.d.ts](https://github.com/selfrefactor/rambda/commit/d916411dc2a5a7bf2c928eedf3164a39e028af26#diff-b52768974e6bc0faccb7d4b75b162c99L77).

![image](https://user-images.githubusercontent.com/7110786/63368779-e7935980-c37e-11e9-8f25-8800a8124fc6.png)

I don't know how to proceed to open a PR, so I've opened an issue :sweat_smile:

**Comment by selfrefactor** [comment]
Nice catch. I will fix it and publish it with `3.0.1` 
Thank you

**Comment by selfrefactor** [comment]
Just published
