### ISSUE TITLE
Typings for curry are broken

### ISSUE THREAD

**Issue by squidfunk** [selfrefactor/rambda#263]
The typings for `curry` seem to be broken:

<img width="632" alt="Bildschirmfoto 2019-09-25 um 19 33 29" src="https://user-images.githubusercontent.com/932156/65625091-7113f800-dfcb-11e9-96f0-07fc7592a61b.png">

Where should the `Curry` namespace come from? I think we should just include `ts-toolbelt` and use it's curry typing, see: https://github.com/pirix-gh/ts-toolbelt/blob/7eb15560101bae9b77b805fe538f020dc177c404/src/Function/Curry.ts#L52-L60

`ramda` does exactly the same.

**Comment by selfrefactor** [comment]
Thank you for the suggestion. I will try to apply it before the end of the week. One issue is that I will have to manually copy `ts-toolbelt` as `Rambda` shouldn't have any dependency, but that is not a big hurdle. Once again thank you.

**Comment by tonivj5** [comment]
Why not use ts-toolbelt as dependency?

**Comment by selfrefactor** [comment]
Because that would influence users that are not using Typescript. Ramda doesn't have such problem, as their typings are separate package.

**Comment by tonivj5** [comment]
I think it isn't influence users, users that are not using typescript are benefiting from typings (through IDE) without any effort.
![image](https://user-images.githubusercontent.com/7110786/65686207-22ff0300-e064-11e9-87c7-f75db81b54e5.png)

ts-toolbelt shouldn't be an inconvenient for javascript users, it should improve their UX

**Comment by selfrefactor** [comment]
I agree with the above, but my idea is to simply include it without touching `package.json` 
At the end, we should have both - using ts-toolbelt and not having production dependency.

**Comment by tonivj5** [comment]
Although I still think that ts-toolbelt should be in package.json :sweat_smile:, I understand you, thanks for discuss it :smile_cat:

**Comment by selfrefactor** [comment]
I just made a commit that addresses this issue. This issue will be closed once version `3.2.0` is out.
