### ISSUE TITLE
Migrate to ES modules

### ISSUE THREAD

**Issue by vlad-zhukov** [selfrefactor/rambda#27]

**Comment by selfrefactor** [comment]
Can you please provide some benefits for the migration? Or it is more of style related issue?

**Comment by Vlad-Zhukov** [comment]
It's format to be supported by browsers and Node soon. However the main benefit right now is tree-shaking.

Would you like me to send a PR?

**Comment by selfrefactor** [comment]
Thank you for the clarification.
Yes, PR will do good if you have the time for that.

**Comment by selfrefactor** [comment]
That was nice to create smaller bundle. It feels like a win situation.
Is there anything left with this issue or should we close it?

**Comment by Vlad-Zhukov** [comment]
I was planning to convert all files to ES modules, with it I expect bundles to be even smaller and more tree-shake friendly. 

What do you think about it? Do you like ES modules or prefer to stick with CJS?

**Comment by selfrefactor** [comment]
ES modules for the win :)

**Comment by Vlad-Zhukov** [comment]
@selfrefactor do you mind moving bundled files to `dist` folder and excluding it from the git?

**Comment by selfrefactor** [comment]
No, I don't mind. 
But I am not sure why you want them excluded from the git.
