### ISSUE TITLE
Module error with _ts-toolbelt

### ISSUE THREAD

**Issue by bjufre** [selfrefactor/rambda#287]
Hello,

I've updated `rambda` to `3.2.5` in an angular project. And it all seemed good until I tried to run the application or storybook inside the project and started getting an error with `_ts-toolbelt`.

I'm attaching a screenshot for a clearer picture of the error I'm explaining:
<img width="765" alt="Screenshot 2019-10-27 at 11 18 58" src="https://user-images.githubusercontent.com/22913276/67633117-16144000-f8ac-11e9-87f4-4616fb4ca316.png">

Any help would be welcome as this is blocking any further development at this stage.

~ bjufre

**Comment by selfrefactor** [comment]
Try with `3.3.0` as it should work. Thank you for bringing it up. Let me know if the issue is gone.

**Comment by bjufre** [comment]
@selfrefactor That solved the issue! Thank you very much man!

**Comment by selfrefactor** [comment]
You are most welcome. Just keep in mind that `3.3.0` is in fact `4.0.0`, i.e. there are breaking changes listed in `CHANGELOG.md`. Nothing drastic, but I just wanted to inform you.
