### ISSUE TITLE
More information about placeholder and flip

### ISSUE THREAD

**Issue by MarcoWorms** [selfrefactor/rambda#3]
I'm curious, since partial application is a powerful feature for composing new functions, why haven't you added `R.__` or `R.flip`?

**Comment by selfrefactor** [comment]
I also want them to be part of Rambda as they could be very powerful methods.

I add a label 'enhancement' to this issue and I will keep you up-to-date with the progress.

**Comment by MarcoWorms** [comment]
Awesome! :D

**Comment by selfrefactor** [comment]
Update - R.flip is ready as well as R.curry but both will work only for functions with maximum 3 arguments. This limitation has influence mostly when you try to curry or flip your own functions. 

As all Rambda methods has maximum 3 arguments, R.flip will work just fine with all of them. 

The code is now only in the source file - rambda.js as I want to create some more tests, before pushing it forward.

As for R.__ - I will see what can be done and get back to you.

**Comment by selfrefactor** [comment]
R.__ is not possible implement without rewriting the whole library and to me is seems like overkill.

Also for R.flip - it will be added to Rambdax, which is library in development, that extends Rambda with more methods. 

I feel that as more options we have, as easier is to write hard to read code.

Still, I thank you for the suggestion and I hope you understand my reasoning. 

If your code style requires R.__ and R.flip, then you really should switch to Ramda. 

Rambda purpose is to offer only the very simple methods of Ramda. In this context R.pluck is much more needed. It is actually ready and will be added once I am done with the tests.
