### ISSUE TITLE
Adding date and libs versions of benchmark results

### ISSUE THREAD

**Issue by dpren** [selfrefactor/rambda#305]
Cool library!

In the table under _"advantages > speed"_, I'd suggest adding some date / version info for Ramda and Lodash. I had to gitblame the docs to make sure it was up to date.

I would also clarify whether or not you're using currying in Lodash. Especially considering `lodash/fp` was a thing at one point.

**Comment by selfrefactor** [comment]
All sound like very good suggestions. I will try complete all of them in the coming week. 
As for lodash/fp and curring - I will write that most of benchmarks results are without curring, but I will try to add curried methods to the benchmark results

**Comment by selfrefactor** [comment]
What I'd do is to add for all methods tested only for Ramda and Ramda, to be called with and without curring. As for `lodash-fp` - I will have to disregard your suggestion in this direction as the package for what I see is deprecated.
