### ISSUE TITLE
why not add ts-toolbelt as a dependency?

### ISSUE THREAD

**Issue by millsp** [selfrefactor/rambda#330]
Hi, I created the ts-toolbelt. I came accross your project and I just wondered why didn't you add my project as a dependency?

**Comment by selfrefactor** [comment]
Because I wanted `Rambda` to stay dependency free, but still be able to provide Typescript definitions. If I do go with the case of exporting these definitions as separate library(i.e. @types/rambda), then I won't have any issue with adding `ts-toolbelt` as dependency. I hope that make sense.

**Comment by pirix-gh** [comment]
Ok, but having a dependency to a type library is not like a having real dependency anyway, I mean it does not have any runtime code. But you are free to copy it of course, there's no problem with that! I just found that it was a strange decision, and was curious to know why :)

Cheers

**Comment by tonivj5** [comment]
Hey @selfrefactor, maybe this issue should be reopened... I come from angular-cli repo, using ts-toolbelt as raw typescript files produce a lot of warnings transpiling my typescript code. 

Could you check my angular issue, it's here: https://github.com/angular/angular-cli/issues/20333

**Comment by selfrefactor** [comment]
Thanks @tonivj5 for your comment. I am reopening this issue and I'll write back when I know how to proceed further.

**Comment by tonivj5** [comment]
Thanks @selfrefactor for the attention 😄

**Comment by selfrefactor** [comment]
I tried to use `ts-toolbelt` as peer/dev dependency, but then all of `dtslint` tests using `ts-toolbelt` broke. 

Then I took the other option, i.e. remove the usage of `ts-toolbelt` types. I am closing this as version `6.7.0` should fix it. Please reopen if it does not.
