### ISSUE TITLE
README.md - list with missing Rambda hyperlink is not working

### ISSUE THREAD

**Issue by AmitMirgal** [selfrefactor/rambda#332]
![Screen Shot 2019-11-30 at 10 10 28 PM](https://user-images.githubusercontent.com/19601060/69908806-88ea6c80-13be-11ea-81c6-f409461f20f3.png)

 **check the list with missing Ramda methods in Rambda** - link seems to be not working.

**Comment by selfrefactor** [comment]
Thank you for bringing it up.

**Comment by selfrefactor** [comment]
Closing as it is fixed
