### ISSUE TITLE
Missing description for anyPass in docs.

### ISSUE THREAD

**Issue by shea-parkes** [selfrefactor/rambda#339]
I think it's fairly straight forward to infer what `anyPass` does from the type signature, examples, and looking at `allPass`, but for completeness it might be nice to add a function description to `anyPass`.

https://selfrefactor.github.io/rambda/#/?id=anypass

**Comment by shea-parkes** [comment]
I did see some other functions without descriptions, but they seemed to be more obvious ones (e.g. `divide`).

Feel free to close this without changing anything though.  Very nice library!

**Comment by selfrefactor** [comment]
@shea-parkes I will add description, as you are right that the method is not obvious enough.
