### ISSUE TITLE
addIndex or another way to get index?

### ISSUE THREAD

**Issue by vendramini** [selfrefactor/rambda#345]
Hi,

What is the best way to get index in functions like `map`? On original `Ramda` we do have a `addIndex` utility. I would like to use this library for performance, but I can't figure out how.

I found this https://github.com/selfrefactor/rambda/issues/85

Whats the best way?

Thanks.

**Comment by selfrefactor** [comment]
Maybe it is better to show example code of what you are trying to accomplish. 

All I know is that Rambda's `map` is passing index as a second argument:

```
test('pass index as second argument', () => {
  let counter = 0
  map(
    (x, i) => {
      expect(i).toBe(counter)
      counter++
    },
    [ 10, 20, 30 ]
  )
})

test('with object', () => {
  const obj = {
    a : 1,
    b : 2,
  }

  expect(map(double, obj)).toEqual({
    a : 2,
    b : 4,
  })
})
```

**Comment by vendramini** [comment]
Yes, you are right. But in case of mapping objects I can't get index:
```javascript
const o = {a: 'test1', b: 'test2'};
    map(
        (val, prop, dic) =>
        {
            console.log(val, prop, dic)
        },
        o
    );
```
What should we do in this cases?

**Comment by selfrefactor** [comment]
I fail to see how I can add `addIndex` as its Ramda implementation suggests that it I need to also add `curryN` and the whole task becomes much more complicated.

One way to solve it is to implement the method yourself like in the example below:

```
import { map } from 'rambda''

test('map with index example', () => {
  const mappedWithIndex = (fn,obj) => {
    let counter = -1
    return map(
      (...inputs) => {
        counter++
        return fn(...inputs, counter)
      },
      obj
    )
  }
  const fn = (x, prop, obj, index) => {
    console.log({index}) // => {index:0} | {index:1}
    return x + 1
  }
  const result = mappedWithIndex(fn, {a:1, b:2})
  console.log({result}) // => {a:2, b:3}
})
```

I will be closing this ticket, but feel free to comment further if you feel like it.
