### ISSUE TITLE
Add chain/flatMap method

### ISSUE THREAD

**Issue by gotenxds** [selfrefactor/rambda#348]
Hya, I've seen previous requests for this but nothing yet, if i'ts fine I'l make a PR to add this

**Comment by selfrefactor** [comment]
I prefer new methods to be added to [Rambdax](https://github.com/selfrefactor/rambdax) - as that was the main reason behind splitting into two separate libraries. I will close this ticket but feel free to open PR on [Rambdax](https://github.com/selfrefactor/rambdax) repo.
