### ISSUE TITLE
Make sortBy receive string as syntactic sugar

### ISSUE THREAD

**Issue by gotenxds** [selfrefactor/rambda#350]
Similar to how lodash does this where you can either pass a function or a string indecating by what property to sort by

```js
R.sortBy(obj => obj.foo , [
  {foo: 1},
  {foo: 0}
])

// just do:

R.sortBy('foo', [
  {foo: 1},
  {foo: 0}
])
```

If this is expected I'm open to add this as a PR if needed

**Comment by selfrefactor** [comment]
It sounds like good suggestion. I'd better take care of the implementation as there are typings tests and documentation that need to be changed as well.

**Comment by ku8ar** [comment]
This is not a good idea. Inconsistent API. And the additional "typeof" will slow down the function.

@gotenxds Currently, you can do it this way:

```javascript
R.sortBy(R.prop('foo'), [
  {foo: 1},
  {foo: 0}
])
```

**Comment by selfrefactor** [comment]
Thank you @ku8ar for helping in this issue. I will have to agree with you on this one and close the issue as `wontdo`.
@gotenxds , if you have further arguments, please feel free to reopen the issue and continue the discussion. I just think that we have way too many differences with `Rambda` and we cannot actually afford to extend further this list.
