### ISSUE TITLE
Add lenses

### ISSUE THREAD

**Issue by synthet1c** [selfrefactor/rambda#372]
Hi,

I want to do a pull request to add lenses to rambda as I need them for a project.

I have completed lens, over, view, set, lensPath, lensProp & lensIndex but would like to know how you want them commited.

Should they all be separate commits and/or separate pull requests for each new function?

The ramda documentation tests all lenses in a single file, is this acceptable or would you prefer individual files for individual functions excluding lens as that is not really testable on it's own.

Regards,

Andrew

**Comment by selfrefactor** [comment]
This is huge as lenses was the most declined request I had to make every 3-6 months. So far there was only suggestion, without anyone going forward to actually implement them. So big thank to you in this context.

As for the test file. I am very fine if you have just one spec for all methods. 

The change will be solid so we'll do a major bump once the changes are approved.

**Comment by synthet1c** [comment]
Awesome, I'll add the documentation and make a pull request hopefully this weekend.

**Comment by selfrefactor** [comment]
If you are writing the documentation, please do so only in `files/README.md` as there is a build process that I run before release.

**Comment by synthet1c** [comment]
I have a couple of issues with building the package following `CONTRIBUTING.md`

* The `src/_typings.spec.js` and `src/_build.spec.js` are failing when running `yarn test`
* The command `yarn prepublish` is not in `package.json`
* I tried to run the benchmarks using `yarn benchmarks` but it only runs a single benchmark for `if_else`
* `docsify` is missing, I tried to install it globally but that didn't work either

Everything is ready to go accept the above.
* methods
* specs
* docs
* benchmarks

https://github.com/synthet1c/rambda

Cheers,

Andrew

**Comment by synthet1c** [comment]
Actually I was able to run the benchmarks by changing the target in `indexProve.js` so benchmarks and docs should be compiled.

**Comment by selfrefactor** [comment]
That is great. You can pull from master as I made some commits lately and there may be minor conflicts.

Contribution documentation is not updated with the very last changes, but good for you that you made it work despite that :)

Looking forward to the so-important PR

**Comment by synthet1c** [comment]
I have merged with your latest changes and submitted the pull request, look forward to the update.

Cheers

**Comment by selfrefactor** [comment]
@synthet1c Once I write typings of lenses, I will release the new version, that will contain your important PR. Feel free to add more suggestion for methods.

**Comment by synthet1c** [comment]
Hey Dejan,

That's great news, I would love to remove ramda from my current project.

I just made another pull request for applySpec. I really want to add
transistors, but I think transistors would need to be different than the
ramda api.

Ramda allows you to use the normal map, filter and reduce in the transistor
as those methods are converted to transistors by default. I think it might
be too much of a change to do in rambda. How would you feel about adding
xmap, xfilter, xreduce to be used exclusively with transistors? (A
transistor is basically a reducing function that can be composed so if you
mapped, filtered and reduced an array it would only do a single loop,
rather than a loop for each action (3 loops).

Cheers,

Andrew

**Comment by selfrefactor** [comment]
Hi Andrew,

I was just about to close the issue as I just released `4.6.0` with your lenses methods.

I will take a look at the new PR and will get back to you. 

As for your suggestion for new methods - I don't mind adding them to `Rambdax` but I prefer to extend the list of differences between Ramda and Rambda.

Rambdax was created for this sole purpose - adding new methods without worrying too much about Ramda spec. You can take a look at it and let me know if adding the new methods there is fine with you.
