### ISSUE TITLE
chain or flatMap missing?

### ISSUE THREAD

**Issue by manubo** [selfrefactor/rambda#38]
Hi, I am looking for a `chain` or `flatMap` function, but can't find it. Is there such a function and if so, what is it's name? If not, is there a special reason and might I submit a pull request to add it?

**Comment by selfrefactor** [comment]
No, `chain` methods is not included, but feel free to submit PR.

While building Rambda, I had to make decision for the most common API methods and that is the reason why you can't find `chain`.

**Comment by selfrefactor** [comment]
I am closing the issue as I haven't received further response. Still, if you send a PR for this method, I will approve it.
