### ISSUE TITLE
add 'forEach' and 'times'

### ISSUE THREAD

**Issue by wagerfield** [selfrefactor/rambda#39]
Hello, me again :)

I would like to see ramda's `forEach` and `times` methods added to `rambda`:

http://ramdajs.com/docs/#forEach

http://ramdajs.com/docs/#times

I use these methods all the time and am missing them dearly from `rambda` :'(

**Comment by selfrefactor** [comment]
Hello, mate!

Thanks for the suggestion - it will be done faster than your previous request as I have more free time now. 

Just to inform you that Rambda has now Typescript definitions by default in case you use Typescript.

**Comment by selfrefactor** [comment]
So, the two methods are added in version 0.9.3

Note, that unlike `Ramda`'s **forEach**, Rambda's one doesn't dispatch to `forEach` method of `arr`. If you need this functionality, please let me know and I will add it.

I will close the issue once you confirm that this version of `forEach` is fine with you.

**Comment by selfrefactor** [comment]
Check [https://github.com/ramda/ramda/blob/master/test/forEach.js](https://github.com/ramda/ramda/blob/master/test/forEach.js)

There we have the following test, which won't pass with Rambda's `forEach`

`
  it('dispatches to `forEach` method', function() {
    var dispatched = false;
    var fn = function() {};
    function DummyList() {}
    DummyList.prototype.forEach = function(callback) {
      dispatched = true;
      eq(callback, fn);
    };
    R.forEach(fn, new DummyList());
    eq(dispatched, true);
  });
`

**Comment by selfrefactor** [comment]
I am closing the issue, but feel free to comment if there is need to.
