### ISSUE TITLE
Modifying arguments

### ISSUE THREAD

**Issue by dacz** [selfrefactor/rambda#4]
Hi, fan of ramda and looking for smaller and faster implementation, arrived to your rambda. I was curious about the implementation and I'd like to ask: for example `prepend` method (as far as I can see in the code) modify the argument (the array). The statement `const clone = arr` do not clone array, co modifying `clone` will modify the `arr`.

Or am I wrong...?

BTW: I like the way you curry most of the functions. Not sure about if it can lead to some issues (arguments are passed to the function but undefined), but as a trade-off why not.

**Comment by selfrefactor** [comment]
Great issue and thank you for the detailed explanation.
I will look onto it and get back to you in a few hours.

As for my curry trade-off - I learned my lesson that we can't have everything and better fit with the best case scenario. 

You are absolutely right that if undefined is passed as argument, most of the Rambda's methods will break. 

This didn't happen to me through my practice and I can say that I use Rambda on daily basis.

One solution is Flowtype(sorry I am not Typescript fan) as Ramda typings could be used for Rambda as well.

**Comment by selfrefactor** [comment]
Spon on - it does modify of course. I should used Array.from

Bugfix will be deployed within hours

**Comment by selfrefactor** [comment]
I am closing the issue as bugfix is deployed.

It was a childish mistake, as I use Array.from on most of my clone declarations. 

Thanks again for the help.

**Comment by dacz** [comment]
Thanks @selfrefactor . I really like your idea to have lightweight ramda clone.

Regarding to `Array.from` ... it was new to me. I usually use `concat`. It has better browser support and according to my tests it's much faster. I made small primitive perf test ( this gist: https://gist.github.com/dacz/a9af8b96f2f607fc8f96d0bc01f2eb7b ). Maybe it would be better to clone arrays.

**Comment by selfrefactor** [comment]
Much faster indeed :)

Do you want to do a PR or you leave the pleasure to me?

**Comment by dacz** [comment]
I played with adjust, too... and updated gist.

I'm happy you see it valuable. Pleasure is yours, if you want. I'm happy to help.

Happy to see rambda as a fast a lightweight toolbox for me in a short time. What do you think to make it consisting of each function separate file? It would enable to optimize even bundle size to import just functions one needs.

**Comment by selfrefactor** [comment]
I accept your recommendation and now methods are separated in files, so you can further optimize the size of your bundle. 

Good luck and thanks again for your nice words. 

I will close the issue, but if you have further feedbacks, please continue the discussion.
