### ISSUE TITLE
groupWith omits value

### ISSUE THREAD

**Issue by mirrec** [selfrefactor/rambda#410]
Hello,

thank you for this library, I really like it.
I have found surprising behavior of `groupWith` function.

Example:

```js
import * as R from 'rambda'

R.groupWith(R.equals, [1, 2, 2, 3]))
// => result: [[1], [2, 2]]
// => expected: [[1], [2, 2], [3]]
```

Do you know about this behavior? Because I have found example over here. https://github.com/selfrefactor/rambda/blob/master/files/failing_ramda_tests/groupWith.js

Tested on versions `4.5.0` and `5.0.0`.

**Comment by selfrefactor** [comment]
Thank you for reporting this bug. It is fixed in the new `5.1.0` version.
