### ISSUE TITLE
omit on large objects is dramatically slow

### ISSUE THREAD

**Issue by clicman** [selfrefactor/rambda#420]
```
// Test object generation
const obj = {
}
for (let i=0; i<10000000; i++) {
  obj[`key-${i}`] = i;
}

//. Omitter
const toOmit = [ 
  'key-1000',
  'key-100000',
 ]
```

Result:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1079535/78868243-c3e76580-7a6c-11ea-95e2-44ffcb443d54.png">

**Comment by selfrefactor** [comment]
Thank you @clicman for reporting that. It is a good catch and I will into it and keep you informed on the progress.

**Comment by synthet1c** [comment]
That was my mistake, I labeled the tests incorrectly, Rambda is the fastest!
```
const converge = [
  {
    label : 'Rambda',
    fn    : () => {
      const fn = Ramda.converge(Ramda.multiply, [
        Ramda.add(1),
        Ramda.add(3)
      ]);

      fn(4)
    },
  },
  {
    label : 'Ramda',
    fn    : () => {
      const fn = R.converge(R.multiply, [
        R.add(1),
        R.add(3)
      ]);

      fn(4)
    },
  },
]
```

I can do a pull request if needed, but I don't know the full process around publishing new methods so I will probably miss something in the building of the dist files.

**Comment by selfrefactor** [comment]
Hi @synthet1c 

Thank you for getting back to me. The current info is irrelevant as all benchmarks will be recalculated my WIP branch is ready. I can ask for your review of the contribute guide, as I see that you may give a valuable feedback. I am closing this then and once I am ready with the guide, I will tag you for PR review if that is fine with you.

**Comment by synthet1c** [comment]
Hey Dejan,

Yeah sounds good.
