### ISSUE TITLE
missing typedefs for newly added `converge` and `curryN`

### ISSUE THREAD

**Issue by VinSpee** [selfrefactor/rambda#425]
> Module '"./node_modules/rambda"' has no exported member 'converge'.
> Module '"./node_modules/rambda"' has no exported member 'curryN'.

looks like these were missed, there is no export for them in `index.d.ts`.

**Comment by synthet1c** [comment]
Dejan opted to leave them out as there are no typescript definitions, unfortunately, I don't yet know typescript to be able to contribute it.

You can access them directly from the source.
```
import { converge } from 'rambda/src/converge'
import { curryN } from 'rambda/src/curryN'
```

**Comment by selfrefactor** [comment]
@VinSpee I will try to add them soon.

**Comment by selfrefactor** [comment]
Added with `5.1.1`
