### ISSUE TITLE
Add R.when

### ISSUE THREAD

**Issue by joeyfigaro** [selfrefactor/rambda#430]

**Comment by selfrefactor** [comment]
I will add it but I am in the middle of something so it will take maybe two weeks before. It is not the reason of the method itself, rather than changing how methods are added and I need to finish it before moving forward.

**Comment by joeyfigaro** [comment]
@selfrefactor not a problem, mate—at your leisure/convenience. :)

**Comment by selfrefactor** [comment]
Released with `5.3.0`
