### ISSUE TITLE
Broken index.d.ts

### ISSUE THREAD

**Issue by kevinbeal** [selfrefactor/rambda#45]
Using Typescript 2.5.2, errors are emitted because of the syntax used in the definition file for this project.

On rambda 0.9.3, in index.d.ts, on lines 387 and 388, the syntax is wrong.

```typescript
without(listToOmit: any[], originalList: any[]): list: any[];
without(listToOmit: any[]): (originalList: any[]) => list: any[];
```

I'm not an expert on Typescript, but `list: any[]` at the end looks like a mistake. 

The error specifically is `Expecting new line or semicolon`. Because this line is broken, you get other errors down the road, like `TS2304: Cannot find name 'without'.` which is a method I'm assuming was added recently.

**Comment by selfrefactor** [comment]
Thank you for finding this bug.  The bug is fixed in the new version `0.9.5`.
