### ISSUE TITLE
Typescript error. Parameter implicitly has an 'any' type.

### ISSUE THREAD

**Issue by mrKimura** [selfrefactor/rambda#458]
node_modules/rambda/index.d.ts:797:68 - error TS7006: Parameter 'obj' implicitly has an 'any' type.

`
export function propIs<P extends string>(target: any, property: P, obj): <T>(obj: Record<P, T>) => boolean;
`

**Comment by selfrefactor** [comment]
Fix is on its way. Thank you for reporting that.

**Comment by selfrefactor** [comment]
I just published `5.4.1` but I am still unsure that you won't get it again, as you didn't provide an example code.

I just imported `R.propIs` definitions from `@types/ramda` so it should be fine, but please let me know if that is not the case.
