### ISSUE TITLE
Breaking changes on patch update

### ISSUE THREAD

**Issue by madjam002** [selfrefactor/rambda#46]
`0.9.7` was published recently which now bundles JS which is ES6 rather than ES5.
This is a breaking change and therefore should be a major version bump due to consuming projects now requiring an ES6 compliant environment.

Would it be possible to revert these changes and release a new patch, and then release the change to ES6 as a major version bump (e.g `1.0.0`)?

**Comment by selfrefactor** [comment]
OK, so you want me to release 0.9.8 which will be compiled to ES5 and then switch to ES6 and publish 1.0.0

That is nice way to satisfy both words and I appreciate your input on the matter.

`0.9.8` will be released within the next 24 hours

**Comment by madjam002** [comment]
Yeah pretty much, that way those of us who are pulling down 0.9.x will get the ES5 version which won't break anything, and then upgrading to 1.0.0 will be ES6. To be fair I think if your major version is `0` people just tend to put breaking changes as the minor version bump, e.g `0.10.0` but personally I always increment the major version as that's following semver a bit more strictly.

Thanks for this :smiley:

**Comment by selfrefactor** [comment]
So `0.9.8` is published and it should be ES5 compatible. I leave the issue open so you have time to report if that is not the case. Once again, thanks for bringing this up.
