### ISSUE TITLE
median should not work for not number types

### ISSUE THREAD

**Issue by dancsee89** [selfrefactor/rambda#461]
It's a [x] Bug

IF `median()` function is called with any, not number type, it is still executed, and returns wrong results. (e.g. strings are still compared, and processed in alphabetical order)

IT should not work for any other types, since it's confusing, I recommend returning with `NaN` in these cases.

I made the fix, and wrote unit tests as well, but couldn't open a PR with it, so here it is, if you're willing to review it:

```javascript
export function median(list){
  const len = list.length
  if (len === 0) return NaN
  if (!list.every(item => typeof item === 'number')) return NaN
  const width = 2 - len % 2
  const idx = (len - width) / 2

  return mean(Array.prototype.slice
    .call(list, 0)
    .sort((a, b) => {
      if (a === b) return 0

      return a < b ? -1 : 1
    })
    .slice(idx, idx + width))
}
```

Unit tests:
```javascript
test('median', () => {
  expect(median([ 2 ])).toEqual(2)
  expect(median([ 7, 2, 10, 9 ])).toEqual(8)
  expect(identical(NaN, median([]))).toBeTrue()
})

test('median, if not called with number type', () => {
  expect(median([1, "foo"])).toEqual(NaN)
  expect(median([1, true])).toEqual(NaN)
  expect(median([1, undefined])).toEqual(NaN)
  expect(median([1, null])).toEqual(NaN)
  expect(median([1, {} ])).toEqual(NaN)
  expect(median([1, NaN])).toEqual(NaN)
})
```

**Comment by selfrefactor** [comment]
@dancsee89 Thank you for opening the issue. Seems like a valid question and I will get back to you later with my review.

**Comment by selfrefactor** [comment]
I run your test against Ramda implementation of `median` and it fails, which means that this change will add to the differences between the two libraries. Maybe it is not the response you expected, but I prefer not to add to the differences list, as there is a risk to grow too long to comprehend. 

If you can pursue `Ramda` to make this change, then I will have no problem of accepting your change. As the things stands, I will have to close the issue. Feel free to comment, even though I am closing the issue.
