### ISSUE TITLE
flip doesn't work when arity > 2

### ISSUE THREAD

**Issue by romgrk** [selfrefactor/rambda#464]
This is a difference with ramda and should either be documented as such or be made compatible.

If it's not made compatible, a more reasonable behavior than `return undefined` should be used, eg `throw new Error("flip doesn't work with arity > 2")`.

https://github.com/selfrefactor/rambda/blob/f8f389549bd03a59b218009117952b318d66932e/src/flip.js#L1-L11

Note: just reviewed the doc, there is a small box saying `Reason for the failure is...` at the bottom of the `flip` section, but it doesn't grab the attention enough, usually a red flair or a warning icon is used in this kind of context

**Comment by selfrefactor** [comment]
I agree that the method the least should throw instead of returning `undefined`. 

The limitation of `R.flip` was listed before in `Differences between Rambda and Ramda` section and was removed from there recently.

I thank you for pointing out that `Reason for the failure is... ` section needs to be a bit more obvious and I will add a :boom: emoji so it reads ':boom: Reason for the failure is... '.

As for R.flip - I wll try once again to make it work for 3 arguments and if I cannot make it, at least the function will throw.

**Comment by romgrk** [comment]
Here is a version that works with 3 arguments:

```javascript
function flipExport(fn) {
  const flipedFn = (...input) => {
    const missing = fn.length - input.length;

    if (missing <= 0)
      return fn(input[1], input[0], ...input)

    if (input.length === 0)
      return flipedFn

    if (input.length === 1)
      return curryN(missing, (...rest) => {
        const args = [rest[0], input[0], ...rest.slice(1)]
        const result = fn(...args)
        return result
      })

    // input.length >= 2
    return curryN(missing, (...rest) => {
      const args = [input[1], input[0], ...input.slice(2), ...rest]
      const result = fn(...args)
      return result
    })
  }

  return flipedFn
}
```

However it requires `fn` to have its `.length` set the to correct value, so other functions in rambda that use `curry` don't work (e.g. `assoc`) because `curry` drops the length :/
One easy fix could be to re-implement `curry` in terms of `curryN`:

```javascript
function curry(fn) {
  return curryN(fn.length, fn)
}
```

**Comment by selfrefactor** [comment]
Sounds good to me. Can you open a PR for that. Just edit `source/flip.js`

**Comment by selfrefactor** [comment]
Actually, I could make your solution work, so I increased the supported arity of `Rambda.flip` to 4. I could wait a few days before releasing the next version, so feel free to open a PR if you want to.
