### ISSUE TITLE
Docs: suggestions

### ISSUE THREAD

**Issue by romgrk** [selfrefactor/rambda#465]
1. Add `rambda` to the page so one can drop in the console from the doc page and use it
2. Add a search box like ramda has

**Comment by farwayer** [comment]
Searchbox will be very cool improvement. I'm using ramda page for it now.

**Comment by selfrefactor** [comment]
@romgrk Can you explain point 1 with other words as I fail to fully understand it.

Currently I am building new documentation with Angular and I will add many features I feel are missing in `docsify` and `markdown`. Search box and filter methods by type are among them. I will keep the issue open and I will close it once the documentation application is ready.

**Comment by romgrk** [comment]
Awesome :) What I mean by point 1 is that you can use `R.methods` from the browser console in ramda docs:

![Screenshot from 2020-05-29 17-33-59](https://user-images.githubusercontent.com/1423607/83307296-68b33300-a1d2-11ea-9d88-835a2c77de3d.png)

**Comment by selfrefactor** [comment]
The future documentation site should have this feature without extra work, as it will have REPL inside it, i.e. it won't be a separate site as it is now. This means, that what you show in the screenshot, will be possible.

**Comment by selfrefactor** [comment]
I am closing this issue in favor of `rambda-docs` issue - https://github.com/selfrefactor/rambda-docs/issues/2 as documentation site is developed there
