### ISSUE TITLE
Many benchmarks are wrong and do not reflect reality

### ISSUE THREAD

**Issue by farwayer** [selfrefactor/rambda#475]
First of all thank you for the great library! I used it in many projects.

But rambda is not so fast as you can think. Many popular functions are much slower than ramda and lodash. The reason of the misconception is in wrong benchmarks.

Lets start from theory. Most functions for processing data consist of two stages: **initialization** and **processing**. In initialization part fn checks data type, arity, makes some preinitializaton etc. In main part fn processing data. Performance of both is important and they should be as fast as possible.

If you pass a lot of data to function than processing stage becomes most important. But initialization stage is important too for use case when you are calling function very often. For example filtering small inner arrays of large list:
```js
map(filter(), [[1,2,3], [4,5,6], ... hundreds of thousands inner arrays ...])
```
Filter will be called many time with small data set.

So to test performance of both stages we need to have two tests: in first we pass a lot of data (testing processing stage) and in second we pass empty data set to execute all initialization checks but skip processing (testing init stage). Rambda in benchmarks uses only variant closest to init testing (several items passed only).

And some another important things:
1. All executing branches should be covered for worst cases (or at least for the most commonly used). For example condition for `filter` should always return true to fully test performance of adding items to new array/object.
2. User code passed to function must be as fast as possible. To correctly testing speed of fn not user code. Ideally something that VM can optimize to const like noop function or function always returns true/false.

Now I will show some proof of wrong benchmarks:
1. **find**
- empty array (**init stage** testing)
```js
  Rambda:
    210 927 688 ops/s, ±0.77%   | fastest
  Ramda:
    3 244 120 ops/s, ±1.60%     | slowest, 98.46% slower
  Lodash:
    21 610 387 ops/s, ±1.27%    | 89.75% slower
```
Yahoo! Fastest. Because no init (only arity check). Lets test with more data...
- 10k items with const false predicate (**processing stage** testing)
```js
  Rambda:
    12 524 ops/s, ±1.54%    | slowest, 93.88% slower
  Ramda:
    204 510 ops/s, ±1.18%   | fastest
  Lodash:
    144 455 ops/s, ±0.82%   | 29.37% slower
```
But wait...

![2020-05-30-221358_521x55_scrot](https://user-images.githubusercontent.com/2343101/83337331-02f2a400-a2c3-11ea-86b6-ba161da0bf43.png)

2. **reduce**
- empty array
```js
  Rambda:
    9 534 810 ops/s, ±2.80%     | 94.44% slower
  Ramda:
    5 777 626 ops/s, ±1.78%     | slowest, 96.63% slower
  Lodash:
    171 437 207 ops/s, ±0.96%   | fastest
```
Ok, init much slower than for lodash and the same as ramda. What about processing performance?
- 10k items with noop reducer
```js
  Rambda:
    9 634 ops/s, ±3.09%     | slowest, 95.4% slower
  Ramda:
    209 617 ops/s, ±1.07%   | fastest
  Lodash:
    12 152 ops/s, ±1.12%    | 94.2% slower
```
And then:

![2020-05-30-222623_529x52_scrot](https://user-images.githubusercontent.com/2343101/83337509-9aa4c200-a2c4-11ea-9b01-4574b69fc446.png)
In reality ramda is fastest and ramda is 95% slower.

I can help with making rambda fastest in the west (saw many places in code where optimization can be done). But we need to add several benchs for functions.

As starting points: #472 #473 #474. No generated files, only source changes.

**Comment by cjk** [comment]
Good point. I also noticed the speed difference between Rambda und Ramda vanished or inverted, as data-sizes being processed increased.

**Comment by selfrefactor** [comment]
@farwayer I just approved all of your PRs and I'll try to improve the benchmarks to fix the raised issue. If you have ideas even for a single benchmark update(like R.find), that will make it easier to apply the same pattern to all of the benchmarks. Thank you for this issue and for the PRs. For contributors like you, I will dedicate a special section as these changes are important.

**Comment by farwayer** [comment]
@selfrefactor Can rework benchs to have several tests with labels for one function? Examples bellow.
**Bench processing performance**
```js
const fn = R.F
const list = R.range(0, 10000)
const find = [
  {
    label : 'Rambda',
    fn    : () => {
      R.find(fn, list)
    },
  },
...
]
```
**Bench initialization performance:**
```js
const fn = R.F
const list = []
const find = [
  {
    label : 'Rambda',
    fn    : () => {
      R.find(fn, list)
    },
  },
...
]
```

**Comment by farwayer** [comment]
And it would be nice to add testing built-in functions like `arr.find()`, `arr.filter()` to comparation.

**Comment by selfrefactor** [comment]
Add native to benchmark is a good idea. I haven't thought about it. Unfortunately, documentation of this project is tightly coupled with benchmarks being in a single file, so we'll have to work around this limitation.

Thank you for the provided example. I can try to replicate your two example cases in a single file. I can create a PR for one of the method's benchmark and I can refer you as reviewer. Or if you want, I can wait for your suggestion.

**Comment by farwayer** [comment]
Yes, it will be nice

**Comment by selfrefactor** [comment]
I will have to change how benchmark files are used during the generation of the markdown file. It should have option for method to be tested against two setups(fast and slow). 

For now I created a new command `yarn benchmarkx` which allow to run all benchmarks inside `scripts/run-benchmarks/experimental`. This way, we can start creating new benchmarks, even though the new results won't be yet displayed.

**Comment by farwayer** [comment]
It will be better if we can have several benchs for one function in one file.
And I noticed you replaced 
```js
const len = list.length
while (index < len){
```
with
```js
while (index < list.length){
```
in find function.
Second variant is slower because of accesing `length` property every step of cycle.

**Comment by selfrefactor** [comment]
My problem with several modes per file is that results are not as clean. Benchmarks are started with `benny` library and this library produce the output, used later in the markdown.

As for your latest comment -  in order to be able to return function from `fn` property, I will have  to check if that is possible. If not possible, how about initializing `list` outside the `fn` property?

```
const list = []

const find_initialization = [
  {
    label : 'Rambda',
    fn    : () => {
      return () => R.find(Utils.F, list)
    },
  },
  ...
]
```

As for the change in `R.find` - I will revert it.

**Comment by selfrefactor** [comment]
I just checked `benny` and the example you suggest won't be possible. `fn` property holds the function to be started; it cannot return a function. What I will do is to generate more complex pipeline for generation of benchmarks. After the pipeline is ready, `R.find` example can be applied to the rest of Rambda methods.

Meanwhile, I'd love to hear if the current state of the new benchmarks if find with you(folder `scripts/run-benchmarks/experimental`)

**Comment by farwayer** [comment]
Check benny API please https://github.com/caderek/benny#api
```js
 /**
   * If the code that you want to benchmark requires setup,
   * you should return it wrapped in a function:
   */
  add('My second case', () => {
    // Some setup:
    const testArr = Array.from({ length: 1000 }, (_, index) => index)

    // Benchmarked code wrapped in a function:
    return () => myOtherFunction(testArr)
  }),
```
Generating list one time can be a bit unfair. List can get into the cache after first test and subsequent tests can work with it faster. This is not surely true, but is possible.

About several benchs in one file: you can generate several benny suites from single file and than parse it. This is not necessary, but it is more convenient to use a single file for single function.

**Comment by selfrefactor** [comment]
Ok, then I will try to see what I can do with the info you gave me. I will try to use one file for all the cases and to return a function as the `benny` example.

**Comment by farwayer** [comment]
One more thing we should do to preliminarily complete new benchs preparation is running benchs for every PR with CI.

**Comment by selfrefactor** [comment]
There are other priorities now, so I am closing this for now. This should be revisited later.
