### ISSUE TITLE
Wrong example for append

### ISSUE THREAD

**Issue by phts** [selfrefactor/rambda#48]
There is [a wrong example for append](https://github.com/selfrefactor/rambda#append)

```js
R.append('foo', ['bar', 'baz']) // => ['foo', 'bar', 'baz']
```

Should be:

```js
R.append('foo', ['bar', 'baz']) // => ['bar', 'baz', 'foo']
```

`'foo'` is added to the end.

**Comment by selfrefactor** [comment]
Thanks for bringing this up.
