### ISSUE TITLE
curryN is very slow

### ISSUE THREAD

**Issue by farwayer** [selfrefactor/rambda#487]
We should review it code and optimize it. After merging #469 all functions that uses `curry` got much slower. I recommend to revert it before we will fix curryN performance.

**Comment by selfrefactor** [comment]
It was related to `R.flip` functionality. I am up for reverting the whole PR and we'll do that the version that will be released today or tomorrow. I will do a compare before and after to confirm your claim, but I am sure you are right about it.

**Comment by selfrefactor** [comment]
I reverted the old `R.curry` functionality and while it is still slower that Ramda, it is an improvement. Released with `5.7.0`
