### ISSUE TITLE
Add insert and insertAll methods

### ISSUE THREAD

**Issue by phts** [selfrefactor/rambda#49]
Please add [`insert`](http://ramdajs.com/docs/#insert) and [`insertAll`](http://ramdajs.com/docs/#insertAll) methods to rambda. And don't forget to update rambdax

Thanks.

**Comment by selfrefactor** [comment]
Those methods are missing on purpose. I see little value in them, but if you submit PR, then I don't mind including them. 

It was similar story with `pipe`, `addIndex`, `pathOr` and `reduce` methods. 

I initially didn't included them but after contributors submitted PRs, there are now part of `Rambda`. If you ask me for my honest opinion, I'd remove all of them, but is my policy is not to reject submitted PR even if I don't fully believe in its value.
