### ISSUE TITLE
`pipe` is not found by Typescript

### ISSUE THREAD

**Issue by phts** [selfrefactor/rambda#50]
Seems to be `pipe` method is missing from `index.d.ts` so Typescript cannot find it, but this method is presented in `modules` folder and in the [documentation](https://selfrefactor.github.io/rambda/#/?id=pipe).

**Comment by selfrefactor** [comment]
I am not big `pipe` fan(the method in Rambda is introduced by PR not by me) so I intentionally omitted the type definitions(I use Ramda definitions as a base). 

In the context that you are opening this issue, I will insert `pipe` definitions with the next release.

**Comment by selfrefactor** [comment]
Fixed with v1.0.4
