### ISSUE TITLE
Length of empty string should be zero, not null

### ISSUE THREAD

**Issue by ivan-kleshnin** [selfrefactor/rambda#514]
Empty string conceptually is an empty array of chars:

![Screen Shot 2020-07-31 at 13 15 56](https://user-images.githubusercontent.com/2128182/89025689-faa0fe80-d32f-11ea-9a9a-2e5af2d99404.png)

Update: it actually returns `NaN` which is displayed as `null` in web REPL.

```
//     "rambda": "^5.9.0",
> let R = require('rambda')
undefined
> R.length('')
NaN
```

**Comment by selfrefactor** [comment]
Thank you for finding this one. The fix will be live with upcoming version `5.10.0`

**Comment by selfrefactor** [comment]
I am closing this issue as version 5.10.0 is published

**Comment by ivan-kleshnin** [comment]
@selfrefactor no problem. If you care about my opinion – I can share with you a few things on how to better (and more correctly) advertise this library. I made a little research recently and got something to add to the discussion. Not something mind-blowing but still. I'm not a kind of person who gives unrequested advices (and maybe you don't like them too) so I'll stop here for now.

**Comment by selfrefactor** [comment]
@ivan-kleshnin I would be interesting for me what are your advises, so if you don't mind, please share them  -I am very much open to such suggestions.

**Comment by ivan-kleshnin** [comment]
### Intro

A few day ago I rewrote one of my project from Ramda to Rambda as an experiment. There were about 50 places where I used Ramda functions. Rewrite went smoothly though I found the above bug and some documentation issues (mostly about argument orders being the reverse of what docs claim). Nevertheless, I'm mostly happy about the rewrite and Rambda being so close to Ramda in terms of API.

### Claimed Benefits

The docs claim the following benefits of Rambda: 
- Bundle size (related to tree shaking)
- Performance
- TypeScript

The build size of Ramda's and Rambda's versions of my project after tree shaking turned out to be mostly identical. I didn't even believe initially and rechecked. But it was true. Numbers were different but very close.

Maybe modern Ramda is perfectly shakeable, or maybe that's because I have a `vendors/ramda.js` file like:

```
import T from "ramda/src/T"
import F from "ramda/src/F"
import adjust from "ramda/src/adjust"
...

export {T, F, adjust ...}
```

which enables tree-shaking even for the cases where Webpack is helpless. Whatever it is, the size of a build bundle is not 
a point to drop Ramda in favor of Rambda.

As for performance, it's tricky. We have this thread: https://github.com/selfrefactor/rambda/issues/475
and, to be honest, we don't expect functional helpers to be a bottleneck in most cases. So it's kinda "ok, meh".

### Real Benefits (IMO)

The size of a library affects not only the **build bundle size** but also **the dev bundle size** and **build time**.
And here the difference is huge. I immediately felt a cut in build time and a jump in dev. page access performance.

#### So I think you should not only mention but emphasize this kinda of difference in docs. 

Teams are tired of slow builds, Devs are tired of slow rebuilds. 
For all the years I do web. dev –  I have a feeling that build and rebuild times are ever growing 😞 

Another potential benefit you didn't mention is that Rambda's source implementations are **pure JS**. 
People who don't know TypeScript yet can read them (if not contribute). All TS stuff sits in a single `.ts` file.
But maybe you're going to change that.

---

To underline, the benefits of Rambda as I personally see them right now are:
- Smaller bundle for DEV performances
- TypeScript out-of-the-box & pure JS sources (a rare combo)
- Good Support (which is visible from issues, I always check Github issues and many people do the same)

*I'd also say that Ramda experiences some dev. stagnation at the moment. Its main creator is not interested in TypeScript (and I understand why – quite an ugly language after Haskell ). But, without "real" static types, its evolution is blocked. So yes, I believe that Rambda can gain some popularity and, who knows, maybe even overgrow its predecessor.*

**Comment by selfrefactor** [comment]
Thank you for the detailed explanation. I will try with your vendor file to check if that influence tree shaking(I expect that it will). Tree shaking repo that compares the build size between Ramda and Rambda is basic Angular project. Even if vendor file helps, I still believe that it is a advantage that Rambda is tree-shakeable without extra efforts. But as I said, I will test with your vendor file and make changes in tree-shaking section.

As for benchmarks - I spend significant effort to make them work and include the results in the documentation so I have to keep that as an advantage, but your feedback was important as I can change the wording to include that the results are not yet fully reliable because of #475 

Smaller bundle for DEV performances - very good point indeed. Still, I will have to prove it somehow. I am thinking of creating a repo that proves this advantage. I just need a big enough project, because you are right that this advantage is best visible in huge projects. If you have a different suggestion about how to prove this advantage, that would be helpful. I can make this top advantage, once there is a way to prove it.

TypeScript out-of-the-box & pure JS sources - I will include your suggestions in the documentation.

**Comment by ivan-kleshnin** [comment]
Thank you. I can cut my current project down to the "playground" barebones and push it to the public.

> As for benchmarks - I spend significant effort to make them work and include the results in the documentation so I have to keep that as an advantage, but your feedback was important as I can change the wording to include that the results are not yet fully reliable because of #475 

I'm not a performance expert, by far, so my opinion has little value. Still, I think adding a note that "performance measuring is tricky" and linking a discussion thread (so you can get more feedback from those in-the-topic) is a good idea indeed.

**Comment by selfrefactor** [comment]
I will try to find a public frontend project using ramda as I want to create a proof that Rambda timing is better than Ramda. So there is no need to create me a `sandbox` of your project, as this will just prove what we already know. I actually included better dev build as an advantage, even if proof is not yet ready.

**Comment by ivan-kleshnin** [comment]
Good. In my case tree-shaking of 3rd party libs were enabled by adding

```
  "sideEffects": [
    "*.css",
    "*.scss"
  ]
```

in `package.json`. This flag is described like something libraries should have but I've been using it seamlessly with applications as well.

**Comment by selfrefactor** [comment]
I will use this info and keep you informed on the progress. I will close the issue and move the discussion to #515 

Once I have a progress, I will tag you in #515
