### ISSUE TITLE
Poll: passing index as second argument to `R.map`

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#534]
The current behavior is that index is passed as second argument. There are few more Rambda methods that does that, so the question is do you prefer to have this option, or you'd prefer to match Ramda logic, which is to pass only the value?

/polls "Option A" "Option B" "Option C"

**Comment by ivan-kleshnin** [comment]
I support the applied change. Yes, more code in some cases but more predictable in others (two-args curried functions aren't filled with `i`), more strict typing, obeys functor scheme.

**Comment by selfrefactor** [comment]
@ivan-kleshnin Thank you for the feedback. I will introduce `R.mapIndexed`/`R.forEachIndexed`/`R.filterIndexed` to Rambdax, so people can switch to the old behavior when needed.
