### ISSUE TITLE
Missing release entries for last few version

### ISSUE THREAD

**Issue by G07cha** [selfrefactor/rambda#546]
Thanks for the library, I find it really handy! I noticed that 6th major release and further are not logged on releases page, I was wondering if documentation about releases were migrated anywhere else?

**Comment by selfrefactor** [comment]
Releases are used mostly to test Typescript definitions before publishing a new NPM version. 

Before every such release, I have to edit `.gitignore` file to include and later exclude `dist` folder. 

Improvement is possible, but it will require `dist` to be published and Github API to allow publish of new release.

The least I can do is add warning in README that releases are not reliable as they are used for testing.

**Comment by G07cha** [comment]
Thanks for detailed reply, really appreciate the time and effort you put into testing releases. I've a couple of ideas that might help but I'm curious about your normal approach to testing releases if you don't mind sharing it?

**Comment by selfrefactor** [comment]
I am glad you understand my position. As I said, I will add info that releases are for test purposes and shouldn't be relied upon. 

As for testing releases - there are `dtslint` and unit tests which theoretically are enough. But when there is a major change, I like to be able to test the pre-release. I do that using code inside `scripts/consume-typings` folder. 

You mention that you have some ideas; do you mind sharing them?

**Comment by G07cha** [comment]
Surely, have you tried linking packages locally?

If you edit `scripts/consume-typings/package.json` and install packages with `yarn --force` you should get latest locally built version alongside with typings. Would this work for you?

```diff
-     "rambda": "5.12.0",
+     "rambda": "file:../../",
```

**Comment by selfrefactor** [comment]
Yes, that would work nicely. Are you sure that `--force` flag is needed as this is first time I see this argument?

**Comment by G07cha** [comment]
`--force` flag would tell yarn to ignore current state of dependencies and reinstall packages regardless, there might be another way to do it but I'm not sure how. The issue is that yarn would quickly compare if all versions match between `package.json`, `yarn.lock` and `node_modules` and because it's a local link it wouldn't be able to detect changes.

**Comment by selfrefactor** [comment]
That makes sense - thank you for the clarification.

**Comment by G07cha** [comment]
My question has been answered a while ago actually, so this issue can be closed.

**Comment by selfrefactor** [comment]
@G07cha  - I just tried to apply your suggestion `"rambda": "file:../../"` but it didn't work as expected. I wanted just to inform you about that.

**Comment by G07cha** [comment]
@selfrefactor would you mind sharing more details about the issue?

**Comment by selfrefactor** [comment]
It was my mistake. Now it works as expected. Thank you.
