### ISSUE TITLE
Converge equivalent?

### ISSUE THREAD

**Issue by Xorhail** [selfrefactor/rambda#55]
Does rambda or rambdax include a converge function that is equivalent to the [converge function in ramda](http://ramdajs.com/docs/#converge)?.

**Comment by selfrefactor** [comment]
I left this types of method on purpose out of Rambda's API so there is no converge equivalent. 

Rambda idea was to be used by people who find this types of method as overkill. 

I found that some issues we generally have in reading others people code is when developers are too smart in places they don't need to be. 

Still, if you interested in creating PR with `converge` method, I'll approve it.

**Comment by Xorhail** [comment]
I'm interested to find out how you would approach certain problems without the functionality of converge. If for instance I wanted to make sure that every element in an array of scores was an integer, I could write something like this in ramda:

```
const data = {
  id: 'some_id',
  scores: [0, '4', 10, 'hi']
}

const parseScores =
  R.converge(
    R.assoc,
    [
      R.always('scores'),
      R.compose(
        R.map(
          R.when(
            R.complement(R.is(Number)),
            R.compose(
              R.defaultTo(0),
              parseInt
            )
          )
        ),
        R.pathOr([], ['scores'])
      ),
      R.identity
    ]
  )

parseScores(data); // '{"id": "some_id", "scores": [0, 4, 10, 0]}'
```

The use of converge with assoc ensures that only the scores property is modified. How would you approach such a problem without the ability to converge?

**Comment by selfrefactor** [comment]
I would go with more direct approach and leaving FP behind in this case, i.e. I will write stupid explicit code.

**Comment by Xorhail** [comment]
Fair enough. I might create a PR in the near future, when I have some time.
Thanks!

**Comment by selfrefactor** [comment]
Ok, that would be great. I will keep the issue open for the time being.

**Comment by MaxSvargal** [comment]
+1, I don't understand how do you live without a kind of methods like converge. 
Because of this I can't move from ramda to rambda =(

**Comment by selfrefactor** [comment]
@MaxSvargal Sorry to hear that, but the PR with `coverge` never arrived and that is why it is still missing in Rambda. As I said above, if PR with this method is submitted, I will gladly accept it. 

As for your funny remark about living without `converge` method - I find myself wanting to write stupider code as it is easier to maintain. `converge` and other similar methods may be fun to use, but they require very specific mind approach, which not everybody are willing to agree with. We write code not only for our present self, but for our future self as well as for the people reading it. Smart code is great looking, but stupid code has its own beauty with its simpleness.
