### ISSUE TITLE
Make the whole rambda type definition immutable

### ISSUE THREAD

**Issue by peterreisz** [selfrefactor/rambda#560]
It is an immutable library, so all the typings should be readonly and ReadonlyArray.

Eslint has a plugin for it (in the `eslint-plugin-functional` package), so it can be automatized:

Minimum eslint config only for this rule:
```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
    es6: true,
    jest: true,
  },
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'functional'],
  extends: [
  ],
  parserOptions: {
    project: './tsconfig.json',
  },
  rules: {
    'functional/prefer-readonly-type': [
      1
    ]
  },
}
```

The following command will do all the work (you will need a tsconfig.json):
```
eslint -c .eslintrc.js index.d.ts --fix
```

On the latest version (6.3.1) it founds and fixes 255 non-readonly types.

**Comment by selfrefactor** [comment]
This is nice suggestion @peterreisz 

I did create a command `immutable` but I have to yet to apply it to TS files. I'll get back to you later, when changes are made to TS definitions.

**Comment by selfrefactor** [comment]
Closing this as changes are applied with version `6.4.0`.
