### ISSUE TITLE
Export types?!

### ISSUE THREAD

**Issue by ivan-kleshnin** [selfrefactor/rambda#561]
Hi Dejan! I'm switching to TypeScript (already using Rambda). Have noticed the following complexities which may be due to my misunderstanding or not. Will appreciate your advices.

Let's take a simple case. I  want to implement `dropEmpty` function on top of Rambda. 

## In JavaScript

```js
const dropEmpty = R.filter(Boolean)
```

### Problem-1

There are no exported types so I have to copy-paste `Dictionary` definition from Rambda sources.

```ts
// copy-paste
type Dictionary<T> = Record<string, T>
```

Is there any reason the following (and not only) is not exported from Rambda?

```ts
type IndexedIterator<T, U> = (x: T, i: number) => U;
type Iterator<T, U> = (x: T) => U;
type ObjectIterator<T, U> = (x: T, prop: string, inputObj: Dictionary<T>) => U;
type Ord = number | string | boolean | Date;
type Path = string | readonly (number | string)[];
type Predicate<T> = (x: T) => boolean;
type IndexedPredicate<T> = (x: T, i: number) => boolean;
type ObjectPredicate<T> = (x: T, prop: string, inputObj: Dictionary<T>) => boolean;
type RamdaPath = readonly (number | string)[];
```

### Problem-2

Polymorhic signatures (inherited from Ramda) cause multiple troubles.

```ts
export function dropEmpty<T>(input: readonly T[]): readonly T[]
export function dropEmpty<T>(input: Dictionary<T>): Dictionary<T>
export function dropEmpty<T>(input : readonly T[] | Dictionary<T>) : readonly T[] | Dictionary<T> {
  if (input instanceof Array) { // <-- this check is necessary to calm down the TS compiler ... @_@
    return R.filter<T>(Boolean, input) // <-- notice the same
  } else {
    return R.filter<T>(Boolean, input) // <-- code...
  }
}
```

Without this check:

![shot](https://user-images.githubusercontent.com/2128182/102196239-4b248d00-3ec8-11eb-840a-d0457a7986ad.png)

Do we really need those overloads? I imagine Elm-like API design where there are separate modules for `List`, `Dict` etc. would be 10x easier in use (both in client and in library code). It could look like this:

```ts
Array.filter(Boolean, input) // <-- when you work with arrays
or
Dict.filter(Boolean, input) // <-- when you work with dicts
```

### Problem-3

Polymorphic overloads are not entirely type-safe. The following code compiles:

```ts
export function dropEmpty<T>(input: readonly T[]): readonly T[]
export function dropEmpty<T>(input: Dictionary<T>): Dictionary<T>
export function dropEmpty<T>(input : readonly T[] | Dictionary<T>) : readonly T[] | Dictionary<T> {
  if (input instanceof Array) {
    return {} // <-- swap readonly T[] with Dictionary<T>
  } else {
    return [] // <-- as nothing enforces their match
  } 
```

### Problem-4

Polymorphic overloads kinda force the client-side to use `function` instead of `=>` (for new functions containing overloads).
There's [a way](https://stackoverflow.com/questions/39187614/typescript-overload-arrow-functions) to do the same with arrow functions but it has its own problems. Overload-less API would be function-type agnostic.

---

To reiterate. I'd suggest to:

1) Export all types from Rambda along with functions 

2) Consider overload-less design for future versions of the library.  By overload-less I mean exlusively overloads related to input data types. Overloads related to currying is a different topic. Going this way, the library would no longer mimic Ramda API design. So it's a had choice between two sets of pros and cons.

If I misunderstand something – pls. tell me. I'm still very new to TypeScript and static typing in general.

**Comment by selfrefactor** [comment]
First, I appriciate the effort in providing so clear to understand issue.

In regard to exporting types - I am unsure that all of internal types and interfaces needs exporting. I will evaluate each one, but in principle I agree that they shoud be exported. At the end, I think that most of those types/interfaces will be exported. I will ping you, once I have something of value to discuss.

In regards to changing to less overloads - I will have to get back to you later for that. My issue when moving too far away from `@types/ramda` that then it might become harder to use their changes and fixes. Still, I am talking this without properly looking into your suggestion. The other issue with change of typings is every change needs to be proven by `dtslint`, which in some cases is can be tricky.

I don't have much time during the week. so my next response will be during the weekend.

**Comment by selfrefactor** [comment]
In regards to your example - I see it as more of an issue of Rambda.filter as anything else.
I have to admit - as time passes by, not having `R.filterObject/mapObject` feels like a controversial and questionable decision, which I should reconsider, even if it comes with the price of major bump.

I can try improve some typings using your example of `R.dropEmpty` as a base and see where it goes. I'll let you know about my progress.

**Comment by ivan-kleshnin** [comment]
> In regards to your example - I see it as more of an issue of Rambda.filter as anything else.

I can agree with that – other functions look more specialized. `R.map` shares the same problem though.

> I have to admit - as time passes by, not having R.filterObject/mapObject feels like a controversial and questionable decision, which I should reconsider, even if it comes with the price of major bump.

Yeah. The problem with this approach is that when you decide to support `Set`, `Map` and other extra objects – naming kinda fails apart. That's why I think **Elm** managed it perfectly – they have clearly separated modules for each major type. 

Eventually, questions like "Where to put `join` – into `Array` or `String`?" tend to arise but they have an easy-to-follow decision guide on this. I can find a link for that if you wish.

**Comment by selfrefactor** [comment]
Just to inform you that I didn't forget about this issue. Next weekend, at most, I will make a release that will include export of internal types and interfaces.

**Comment by selfrefactor** [comment]
Hi Ivan,

I decided that I shouldn't postpone this issue any longer.

Version 6.5.0 export several of internal types and interfaces. You can see the commit above for further details.

I won't export all internal interfaces as I see only few of the makes sense to be exported. Also some types, such as `Partial`, have too common names and could clash with TS native interfaces. Also, some types seems redundant so I'd prefer to first clear them out, before increasing the list of exported internal TS interfaces. 

FYI - there is new major bump on the horizon. The version will include, among other things, moving the iteration of object from `R.map` to `R.mapObject`. This will make Rambda works better with TS. Such change will affect other methods. I share that so you can see that changes are coming. In the process of building `7.0.0`,  I will revisit this issue, even though it is closed. When `7.0.0` hits, I will try not to forget to share the new interfaces in this discussion.

As for `const dropEmpty = R.filter(Boolean)` - I have hard time to produce a working version even if start with brand new definitions. In other words, if I have to implement such function, I'd go to ask the end user to provide the expected output type. My personal experience with Rambda and TS is painful. I stopped using R.compose almost completely and I use Rambda as Lodash, when I am using it in Typescript. I hope version `7.0.0` helps a little, but the pain is there.

As for using more complex TS definitions such as the following:

```typescript
export function foo<T>(input : readonly T[] | Dictionary<T>) {
  if (input instanceof Array) {
    return {} 
  } else {
    return [] 
  } 
} 
```

The way definitions are extracted with `rambda-scripts` from `files/index.d.ts`, such evaluations could brake the pipeline. Also, this way we increase the number of lines for TS definitions and this will influence the design of the upcoming API documentation site.

I am closing the issue, but feel free to write further. Thank you for bringing it up, as it definitely makes sense to export some of the important internal interfaces.

**Comment by ivan-kleshnin** [comment]
Hello, Dejan. Thank you for the clear explanation and for the work you've done! 
My experience with TS and functional patterns in TS is very similar 😒 
I will share updates as I have them.
