### ISSUE TITLE
Question about the benchmarks

### ISSUE THREAD

**Issue by sudoman** [selfrefactor/rambda#569]
Thanks for the cool library. : )

It looks like there are many stats where one system is 99% or 98% slower than the fastest result, but I see none that are 100% or above. My interpretation of "99% slower" is that it takes 199% as long as the fastest case. If this is the meaning, then I wonder why there are none that are over 100% slower (over 200% run time compared to fastest library), etc.

It seems more likely that you have a different meaning in mind with these stats, but I wasn't able to figure out how to interpret them. Perhaps explaining their meaning or how they are calculated would help, but I think that a better solution would be to make them literally accurate, so one can just read the text in the stats table. Thanks : )

**Comment by selfrefactor** [comment]
The numbers are coming from https://www.npmjs.com/package/benny
99% faster means that one value is like 1000000 while the other is like 100, so the first one is faster that the second with 100% - (100/1000000). I hope that answers your question. Take a closer look at **benny** if you have more questions.
