### ISSUE TITLE
anyTrue not exported

### ISSUE THREAD

**Issue by Debdut** [selfrefactor/rambda#573]
I imported like this

```js
import { anyTrue } from 'rambda'
```

I get the following error

```
Error: 'anyTrue' is not exported by node_modules/rambda/dist/rambda.esm.js
```

I searched the `rambda/dist/rambda.esm.js` and it doesn't have any mention of `anyTrue`. All other imports are working correctly!

**Comment by Debdut** [comment]
I see it, just update the docs at https://selfrefactor.github.io/rambda

**Comment by selfrefactor** [comment]
I am closing this as R.anyTrue is part of Rambdax, not Rambda.
