### ISSUE TITLE
So __ is not gonna be added ?

### ISSUE THREAD

**Issue by yairopro** [selfrefactor/rambda#574]
In #3 2017 you said it will need to rewrite the library in order to add the function placeholder __.
Is it possible now ? Or is it on a roadmap ? Or is it completely out of picture to add this feature ?

**Comment by yairopro** [comment]
This question should have been added to the discussions tab rather than in the issues, sorry 😬. I am still not used to the discussions tab, my bad.

**Comment by selfrefactor** [comment]
Thanks @yairopro for bringing this up. 

In retrospection to the issues related to Typescript usage of libraries such as Ramda/Rambda, I am even less inclined to add the placeholder `R.__` method. 

It might be hard to implement in JS, but to describe properly in TS will increase the already complex state of Rambda typings. 

I will close the issue, but feel free to comment further.
