### ISSUE TITLE
dropRepeatsWith() doesn't exist in REPL & usage is wrong in docs

### ISSUE THREAD

**Issue by jasonnathan** [selfrefactor/rambda#575]
Usage is incorrect in the [docs](https://selfrefactor.github.io/rambdax/#/?id=droprepeatswith). Also, `R` in the [REPL](https://rambda.now.sh/?const%20list%20%3D%20%5B%7Ba%3A1%2Cb%3A2%7D%2C%20%7Ba%3A1%2Cb%3A3%7D%2C%20%7Ba%3A2%2C%20b%3A4%7D%5D%0Aconst%20result%20%3D%20R.dropRepeatsWith(R.prop(%27a%27))%0A%0A%2F%2F%20%3D%3E%20%5B%7Ba%3A1%2Cb%3A2%7D%2C%20%7Ba%3A2%2C%20b%3A4%7D%5D) does not contain `dropRepeatsWith`. I checked with `Object.keys(R)`.

Apologies, I intended to submit a PR for the docs but when the REPL failed as well, I couldn't test usage

**Comment by selfrefactor** [comment]
REPL is easy to fix as it needs update to include the latest changes. 

Can you share what exact;ly is wrong in method's usage in docs?

**Comment by selfrefactor** [comment]
I am closing this as I fail to see the wrong usage in documentation. The method indeed is missing in REPL but this will be fixed.
