### ISSUE TITLE
R.uniq should not convert undefined to null in Rambda REPL

### ISSUE THREAD

**Issue by alexander-entin** [selfrefactor/rambda#576]
R.uniq([undefined, null])
// expected result: [undefined, null]
// actual result: [null, null]
// (at least in the [playground)](https://rambda.vercel.app/?const%20result%20%3D%20R.uniq(%5Bundefined%2C%20null%5D))

**Comment by selfrefactor** [comment]
It seems that the issue is related to REPL as I added a new test case in `uniq.spec.js` and it looks that it is working correctly. I will write again once I understand why this happens only in REPL.

**Comment by selfrefactor** [comment]
The reason is that `JSON.stringify([null, undefined])` is equal to `[null, null]` and REPL app is using `JSON.stringify` . I will keep the issue open until I solve the issue.

**Comment by selfrefactor** [comment]
I am currently in a sick leave, but afterwards I will look into the issue.

**Comment by selfrefactor** [comment]
Thanks for the issue; it is fixed now.
