### ISSUE TITLE
Expose `mapObject`, `mapArray`, `filterObject`, etc. low-level functions

### ISSUE THREAD

**Issue by ivan-kleshnin** [selfrefactor/rambda#578]
In many cases TS can not correctly infer `Array` vs `Object` types which becomes problematic for `map`, `filter` and maybe few other highly polymorphic functions. 

Rambda already have `mapArray` + `mapObject` functions and implements `map` in their terms. 
They are even exported but, unfortunately, untyped. 

As a relatively low effort solution, can we add those types to allow end users to decide whether they want to use `map` or `mapObject` directly?

**Comment by selfrefactor** [comment]
I will export them and add a comment to R.map and R.filter that they can use the new methods.

**Comment by selfrefactor** [comment]
On second thought, I'd prefer exposing them in Rambdax. Let me know if that is fine with you.

**Comment by ivan-kleshnin** [comment]
No complaints, I just didn't try Rambdax yet. Are both libraries released/updated at the same time, automatically? (I mean if some change should be in both)

**Comment by selfrefactor** [comment]
Rambdax releases include all of Rambda changes, but the release is triggered only if there is a change in any of Rambdax-only methods. The release is automated where possible, but the process is manual. I'll write again when the issue is fixed and release is made.

**Comment by selfrefactor** [comment]
Requested methods had been added with Rambdax version `7.3.0`.
