### ISSUE TITLE
What makes ramBda faster than ramda?

### ISSUE THREAD

**Issue by mohit61** [selfrefactor/rambda#601]
Hi, I am quite fascinated after looking at the benchmark result, that's awesome work!
I am curious to know why it executes faster than  Ramda, could you please tell me what optimizations have you done?

**Comment by selfrefactor** [comment]
It is a bit hard to write detailed explanation why Rambda is faster, as it is related to internal function which Ramda uses. Rambda uses much less internal functions and it is more obvious what is happening, while in Ramda I see mostly use of internal functions.

I will close the ticket, as I won't be able to react to it, but I finish with source code of random Ramda method to illustrate my point about internal functions:

```
var _curry2 = require('./internal/_curry2.js')
var _dispatchable = require('./internal/_dispatchable.js')
var _dropLast = require('./internal/_dropLast.js')
var _xdropLast = require('./internal/_xdropLast.js')

var dropLast = _curry2(_dispatchable([], _xdropLast, _dropLast))

module.exports = dropLast
```
