### ISSUE TITLE
f.length gives 0 

### ISSUE THREAD

**Issue by mohit61** [selfrefactor/rambda#605]
f.length should give the no. of arguments that function expects, which in the below case is 2, but the output is 0

```
var f = R.compose(R.map, R.multiply, parseInt);
console.log(f.length)
 ```
 
 output:
 `0`
 expected:
 `2`

**Comment by selfrefactor** [comment]
I have a test to showcase this difference, but I couldn't fix it. Will have to close the issue, but feel free to comment further.
