### ISSUE TITLE
Make all functions modules

### ISSUE THREAD

**Issue by wagerfield** [selfrefactor/rambda#61]
Hey @selfrefactor me again—it's been a while!

Would you mind making all exported functions modules—so they can be imported separately?

The functions that are currently only declared in [`rambda.js`](https://github.com/selfrefactor/rambda/blob/master/rambda.js) are:

- [`always`](https://github.com/selfrefactor/rambda/blob/master/rambda.js#L7)
- [`complement `](https://github.com/selfrefactor/rambda/blob/master/rambda.js#L11)
- [`F`](https://github.com/selfrefactor/rambda/blob/master/rambda.js#L26)
- [`identity `](https://github.com/selfrefactor/rambda/blob/master/rambda.js#L35)
- [`not`](https://github.com/selfrefactor/rambda/blob/master/rambda.js#L52)
- [`T`](https://github.com/selfrefactor/rambda/blob/master/rambda.js#L76)
- [`trim`](https://github.com/selfrefactor/rambda/blob/master/rambda.js#L86)

I would like to be able to import these functions from the `lib` like so:

```js
import identity from 'rambda/lib/identity'
```

**Comment by selfrefactor** [comment]
Hi @wagerfield 

Thank you for opening this issue.

When I wrote those shortcuts, I knew that there will be a day, where I will have to redo them. 

So this day seems to be today.

**Comment by wagerfield** [comment]
Hahahaha @selfrefactor—I hope this day didn't come too soon!

**Comment by selfrefactor** [comment]
No, it did not. 

Actually there were some other issues, which I found, so at the end it wasn't such a small issue as it initially looked like.

The requested changes are implemented in version 1.0.12 and I am keeping the issue open till you confirm that it works from your end.

**Comment by selfrefactor** [comment]
I am closing it assuming that everything is ok. Feel free to reopen if that is not the case.
