### ISSUE TITLE
v7.0.0 import fails w/ vite

### ISSUE THREAD

**Issue by Uninen** [selfrefactor/rambda#614]
I have a project that uses [Vite](https://github.com/vitejs/vite) for bundling. Version v6.9.0 of rambda worked fine, but v7.0.0 produces following error: 

`error: [plugin: vite:dep-scan] Failed to resolve entry for package "rambda". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "rambda". The package may have incorrect main/module/exports specified in its package.json.`

..and indeed, package.json seems to point to `./dist/index.esm.js` which doesn't exist in dist.

**Comment by HashDot** [comment]
Same problem for me with next.js. Version 6.7.0 works fine.

**Comment by selfrefactor** [comment]
Thank you guys for bringing this up. I will try to publish a fix soon.

**Comment by selfrefactor** [comment]
I will close the issue, as version `7.0.1` is published with the fix. Please, let me know if the issue persist.

**Comment by Uninen** [comment]
Thank You for the swift response 👍
