### ISSUE TITLE
Move to Typescript

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#62]
There is currently an issue with inconsistent and faulty typings.

One way to solve it is to let Typescript build the definitions.

**Comment by selfrefactor** [comment]
It will be implemented in Rambdax until Typescript has better support for curried functions.

**Comment by selfrefactor** [comment]
Typescript 2.8 will bring the needed change to allow proper declaration of curried functions.

**Comment by thebrodmann** [comment]
Hi,

I don't find any branch for this big change in Rambda. Is it started? If yes how can I contribute?
Also in [CONTRIBUTING](CONTRIBUTING.md), I don't find anything related.

**Comment by selfrefactor** [comment]
Hi,

Not much could be done now. Hopefully Typescript will do something progress on https://github.com/Microsoft/TypeScript/issues/5453 this year. 

This is the blocking issue and as soon as it is solved, the work on moving Rambda to Typescript will resume. The issue remains silent about any suggestion for a timeline, so we are waiting in the limbo.
