### ISSUE TITLE
`applySpec` doesn't play nicely with `pipe`

### ISSUE THREAD

**Issue by rakeshpai** [selfrefactor/rambda#627]
If we use a function constructed using `pipe` as part of an `applySpec` call, it just returns an empty object. 

Here's some code to illustrate the issue:
```ts
import { applySpec, pipe, length } from "rambda";

const array = [1, 2, 3, 4, 5];

console.log(
  applySpec({
    len: length
  })(array)
); // prints { len: 5 } This is fine

console.log(
  applySpec({
    len: pipe(length)
  })(array)
); // prints {} <-- This is unexpected
```

To keep the example simple, I've used only one function in `pipe`, but that shouldn't matter. 

You can try this out [in a codesandbox here](https://codesandbox.io/s/autumn-platform-wg5kz5?file=/src/index.ts:0-276).

**Comment by selfrefactor** [comment]
Good catch and will look into it. As I haven't added the method (https://github.com/selfrefactor/rambda/pull/381), feel free to try to fix it if you want to, as you know as much for this method as I do. Otherwise, I will try to figure out why `__findHighestArity` doesn't behave as expected in your example.

**Comment by selfrefactor** [comment]
The underlying issue was that `R.pipe` wasn't returning the correct length so `R.applySpec` didn't know what arity is the function. The fix was to copy most of `Ramda.pipe` handling. With the upcoming version, this issue will be solved. I will keep the issue open until then.

**Comment by rakeshpai** [comment]
Hey. Just cycling back to this. Nice to know it's fixed. Sorry I couldn't help. Looking forward to the next version!

**Comment by selfrefactor** [comment]
Closing this as version `7.1.0` should fix this issue. Let me know if that is not the case.
