### ISSUE TITLE
All merge functions ignore keys with function values

### ISSUE THREAD

**Issue by aniederer-chatham** [selfrefactor/rambda#628]
Rambda:
![image](https://user-images.githubusercontent.com/56323178/160195576-fa310725-7b98-4427-897f-0e61d4734bf5.png)

Ramda:
![image](https://user-images.githubusercontent.com/56323178/160195653-e544423d-41ce-46df-80b9-cc26bc3b58cf.png)

Also applies to mergeRight, mergeLeft, and mergeDeepLeft

**Comment by selfrefactor** [comment]
Thanks for filling this issue. I will look into it and get back to you.

**Comment by selfrefactor** [comment]
issue is fixed now
