### ISSUE TITLE
flatMap is missing

### ISSUE THREAD

**Issue by kay999** [selfrefactor/rambda#63]
Why is there no flatMap operation? It's not only very useful, it's also the bind operation for the list monad, so it's kind of heresy to omit it from a "functional" library ;)

There's a "flatten" in rambda, but because it flattens recursively, one can't simply define flatMap as compose(flatten, map). 

So please consider adding a non-recursive shallowFlatten and also 'flatMap' (ideally an optimized one, but one based on map and shallowFlatten would also do).

Also a 'scan' operation (similar to reduce but building a list of the result of each iteration instead of giving just the end-result) would be useful (but far less important as flatMap). 

Another useful operation would be somethink like "any" which would only test for 'undefined' and return the first non-undefined result of the iteration. This is useful to return the first successful application of a value to some operation (similar to 'find' but returning an arbitrary value instead of the found element).

**Comment by selfrefactor** [comment]
Thanks for opening the issue and your suggestions. 

While you explicitly describe your request, it will be much easier for me if you accompany each of them with simple pseudo-code, such as:

```
const result = R.foo({a: 1, b: '2'}, R.type) 
// result is `['Number', 'String']` 
```

In general I am open to implement all of your suggestions, but that will have to wait for Typescript 2.8 to arrive(between 1 and 2 months from now).

Then **Rambda** will switch to **Typescript** and all of method will be rewritten. During this major change, I will implement all of your suggestions. 

I hope you do understand and I will wait for the pseudo-codes.

**Comment by davidjbradshaw** [comment]
Why the switch to TypeScript? Surely that will just cut down on the pool of people who could help with the project. 

I was just looking at switching to this from Ramda, with the view that I would just implement and contribute any methods that I currently use that are currently missing. If you switch to TypeScript then I think I will just have to fork the project which is a shame.

**Comment by thejohnfreeman** [comment]
I can help you with some of these functions, but can you answer some questions first? I have read the `CONTRIBUTING.md`.

1. ~It seems like you implement functions twice, in both `lib` and `modules`.~ You have a `prepublish` command to build `lib` from `modules`, but why do you commit it? Do you expect contributors to commit it as well?
2. It seems like you haven't migrated to TypeScript yet. Is that right?
3. You have `dissoc` but no `assoc`. Is there an `assoc` under a different name?

I need `assoc` and `flatMap` myself.

**Comment by selfrefactor** [comment]
That is very nice of you to help me out.

Here are the answers:

1. I commit it as it is needed for ES5 support. I don't expect the contributors to run the `prepublish` command.
2. No. Still waiting for varadic support landing in Typescript [https://github.com/Microsoft/TypeScript/issues/5453](https://github.com/Microsoft/TypeScript/issues/5453)
3. `assoc` landed because of someone did a PR. Feel free to add `dissoc` if you need it.
