### ISSUE TITLE
Function Ramda.mergeDeepRight looses methods of target object

### ISSUE THREAD

**Issue by ahtohbi4** [selfrefactor/rambda#636]
Hi there!

I found that the function `mergeDeepRight` looses methods of target object, as opposed to Ramda:

```js
import * as Rambda from "rambda";
import * as Ramda from "ramda";

const target = {
  onError() {},
};

console.log(Rambda.mergeDeepRight(target, {}));
// => {}

console.log(Ramda.mergeDeepRight(target, {}));
// => { onError: f }
```

You can play with that here — https://codesandbox.io/s/jovial-haze-ho958w.

Is it feature or bug?

**Comment by selfrefactor** [comment]
It looks like a feature as the way Rambda does a deep copy has its limitations.

References:

https://code.tutsplus.com/articles/the-best-way-to-deep-copy-an-object-in-javascript--cms-39655

```
JSON.parse(JSON.stringify(target) - doesn't copy functions
```

https://stackoverflow.com/questions/122102/what-is-the-most-efficient-way-to-deep-clone-an-object-in-javascript

https://web.dev/structured-clone/

I'll close the issue, as there is not much I can do, besides adding test to show this limitation.
