### ISSUE TITLE
Doc issues

### ISSUE THREAD

**Issue by HaveF** [selfrefactor/rambda#637]
@selfrefactor I like your rambda ❤️ 

I'm not very familiar with FP, so when I use rambda, I often look the Doc for help. But the doc is a bit hard to search. Normally, I want a function for list, I will go to ramdajs 😂  and use `list` to narrow down the scope, then find what I'm looking for.

![image](https://user-images.githubusercontent.com/54462/171542326-f24a2df4-9f50-4a0a-8b95-f8e363f574d9.png)

For example, I find the `without` function, then went to https://selfrefactor.github.io/rambda/ to search without(because rambda has a little different with ramda)

![image](https://user-images.githubusercontent.com/54462/171542772-e081990e-221f-4c6b-af59-3bb004490188.png)

Then I click 💥 

![image](https://user-images.githubusercontent.com/54462/171542811-70e542ad-5dbf-49b0-935e-e0df0bd4405e.png)

It seems like something url parse problem. Even without this bug, the doc is still hard to read.

Frankly speaking, I do suppose your tool is over underestimate because Doc.

Btw, after some research, I think https://docusaurus.io/ maybe fine for the Doc.

Do you have any idea or plan about the doc?

**Comment by selfrefactor** [comment]
Thanks for the issue report.

I will look into it during the weekend and get back to you. As for using Docusaurus - I am developing Angular application as Rambda documentation site, but I will look into it to see if I can easily use it.

**Comment by selfrefactor** [comment]
thanks for all the recommendations; will take a look at it later and get back to you.

**Comment by selfrefactor** [comment]
fyi, the documentation site is build with `docsify`. Also, I am unable to reproduce the issue. I search with the browser for `without` then I click on the sidebar link and it correctly redirects me. Can you share more info how I can reproduce it?

**Comment by HaveF** [comment]
Oh, that's strange...

After I tried in another browser it is fine. Then I suspect the web extension which I installed...

Finally, I find [ClearURLs 1.24.1](https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk?hl=en) break the page. When I open url `https://selfrefactor.github.io/rambda/`, it will change the url to `https://selfrefactor.github.io/rambda/#%2F=`, after that, all link in the page broken...

Of course, the extension broken https://docsify.js.org/ page too = =;

**Comment by HaveF** [comment]
Ok, If you want me to do some doc work, let me know!

**Comment by HaveF** [comment]
For somebody who stumbled with this issue(use ClearURLs 1.24.1), [see this solution](https://github.com/ClearURLs/Addon/issues/193#issuecomment-1097167330). It works now.
