### ISSUE TITLE
R.where short curcuiting

### ISSUE THREAD

**Issue by nshaikhinurov** [selfrefactor/rambda#648]
Ramda'a `R.where` returns early when first predicate fails. But rambda's one evaluates all the predicates in the spec object regardless if one of them already failed. That may potentially be a performance issue.

**Comment by selfrefactor** [comment]
Thanks for the report. A fix will be published this weekend. I will write again when that happens.

**Comment by selfrefactor** [comment]
done with `7.3.0`
