### ISSUE TITLE
New library that doesn't follow Ramda API

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#653]
It is time to rebrand the library as it makes it very hard for branding and remembering while it is so close to `Ramda`. The new library will not aim to follow Ramda API so that can help in making hard decisions.

`Rambda` will remain as it is, i.e. following Ramda API and receiving updates, but `Rambdax` will receive lower priority and stop receiving regular updates. `Rambdax` will only publish bugfixes and it will be synced with latest `Rambda` releases.

Naming is still ongoing question.

**Comment by selfrefactor** [comment]
I stopped at the name `ripoff`, if somebody has a better idea, then please share it.

**Comment by ivan-kleshnin** [comment]
I like the idea of an experimental parallel project, Dejan. I'm not strong at branding but, as my 5 cents, I can say I like `Roza` 🌹 It's short, it starts with `R` and it seems to not conflict with other projects in the ecosystem.

**Comment by selfrefactor** [comment]
Thank you, Ivan. Yes, I also think that branding is important and `roza` fits it better than other options.
I plan this library to have `Rambdax` as dependency, export its all functions. What is done by now will be used, but the focus won't be that the library is following some other library's API. This means that documentation will no longer aim to convince the visitor that the library is compatible with Ramda API. Of course, there will be information about that, but nothing more. Now, on every step (method description, tests, changelogs) Ramda is main topic; I really want to change that.

I want the new library to be more TS oriented, maybe even be written in TS in order to solve issues with composable functions. In this context, `remeda` is good source as their mixture of `R.pipe/R.filter` is much better and actually this shortcoming made me use less `Rambda` in my own projects.

**Comment by ivan-kleshnin** [comment]
I see. Yeah, I myself stopped to use `pipe / compose` because they don't work properly (not just in Rambda but in other libraries also). For `map` & `filter` appplied to objects I use this override:

```
declare module "rambda" {
  export function mapObject<T, U>(fn : ObjectIterator<T, U>, iterable : Dictionary<T>) : Dictionary<U>
  export function mapObject<T, U>(fn : ObjectIterator<T, U>) : (iterable : Dictionary<T>) => Dictionary<U>
  export function filterObject<T>(predicate : ObjectPredicate<T>) : (x : Dictionary<T>) => Dictionary<T>
  export function filterObject<T>(predicate : ObjectPredicate<T>, x : Dictionary<T>) : Dictionary<T>
}
```

So yes, some hacks are currently necessary and if you know a way to remove them – that's great 👍

**Comment by synthet1c** [comment]
A rebrand would be a great idea!

I can never find the docs or the repo without digging in google.

`vitaljs` would be a cool name, There is another `vital` library but not `vitaljs`. It's not taken on npm and doesn't show up in a google search results. `rosa` is cool though.

**Comment by selfrefactor** [comment]
thanks for the input @synthet1c but I am not big fan of appendixes in name. I don't see much libraries using this approach, even though it is a valid logic when the library without appendix is abandoned. If we go in this direction, then we'll have much more choices such as `funny-js`. We can A/B test  the name and try two names to see which one is more accepted. I will keep posting updates, once I have news in this regard.

**Comment by selfrefactor** [comment]
@FredericEspiau The name should be easy to remember. It doesn't matter that `roza` brings many results, this is expected. More important is word of mouth recommendation and for that available name in JS context is required. Unnecessary mind mapping is not something I am keen on.

As for the pipe suggestion. I will give it a look and respond again.

**Comment by FredericEspiau** [comment]
It depends, I've works at [WebWag](https://www.webwag.com/home), which was created by the former director of Google France and he chose a name hard to remember so people would be forced to remember it and thus get attached to it.

Also, I get frustrated when I look for a library whose name I can't remember because it's a common word, for example yesterday I lost at least a full hour looking for [Fluent](https://projectfluent.org/) because I couldn't find anything as it was such a common word.

But hey it's your project, you do you 😄

**Comment by selfrefactor** [comment]
I get your point @FredericEspiau and I agree, but regarding the name, I am looking for something like Kefir.js

It is a common word, but it is still not that common and there is branding in JS context. I would like to have some relation to functional programming as `Roza` doesn't speak enough about the library topic. 

While writing this, I though if `funky-js` is free and if `funky` is abandoned package. It was true, but then I faced this error:

```
 403 Forbidden - PUT https://registry.npmjs.org/funky-js - Package name too similar to existing package funkyjs; try renaming your package to '@self_refactor/funky-js' and publishing with 'npm publish --access=public' instead
```

So I thank you for the input as it let me try use a better name. I would never know about this NPM restriction without your comment.

**Comment by ivan-kleshnin** [comment]
> I don't like roza as it has a lot of results in Google. 

What's much more important `roza github`, `roza functional`, `roza helpers` have no collisions. 
`react` is also an existing word but people don't have troubles finding it, right? 😉

**Comment by selfrefactor** [comment]
I spend some time finding short word that is not already taken on NPM but very few words are left. I remember the first episode of animated `Dilbert` where they mock the principle that the name is most important thing when starting up a project. Now, that I have idea what `Roza` will contain and how it will differ from `Rambda`, I am more focused on creating a valuable library, than the name. As I said, I like that it is unique, it is easy to remember, it has relation to my language, we can attach a logo to the project and `rose` is abandoned NPM library. I would still like to have some resemblance about the topic of the library, but for now I don't see any good options.

**Comment by selfrefactor** [comment]
I will be closing this issue as I should have used `discussions` feature instead. I will write again, when `Roza` is ready for test drive. Thanks to all involved.

**Comment by selfrefactor** [comment]
I just deprecated `roza`. Reason is that more I work with objects in Typescript, more I understand that developers better do the heavy lifting themselves in their code base. Moving/hiding this part is not something that I want to encourage. If I have clearer view about what `roza` should be doing, then I might restart it.
