### ISSUE TITLE
Bug: Unused generic type

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [selfrefactor/rambda#654]
Here is a second generic type but it is not used

https://github.com/selfrefactor/rambda/blob/a368ff1636a36c1692b80746f7ca150c4bc4f9bc/index.d.ts#L1309-L1310

**Comment by selfrefactor** [comment]
thank you, this is valid issue and it will be fixed.

**Comment by selfrefactor** [comment]
fixed so I am closing this issue
