### ISSUE TITLE
Unfair size comparison to ramda

### ISSUE THREAD

**Issue by JamesRamm** [selfrefactor/rambda#658]
The latest version of rambda has a package size of 807kb
https://packagephobia.com/result?p=rambda@7.4.0

The latest version of ramda is at 1.06MB
https://packagephobia.com/result?p=ramda@0.28.0

The difference is about ~250KB

Ramda has about 260 functions in it. With some rough calculations we can estimate that adding the missing functionality would take you to _at least_ the same package size as ramda. 

So claiming rambda as a drop in replacement for ramda but with smaller size is fairly unfair. 

I say this in good faith and to try and help other potential ramda converts from wasting time. I spent a good while evaluating this package before finding out that a good number of our most heavily used functions are not available. 

For anyone coming from ramda, the list of missing methods is here:
https://selfrefactor.github.io/rambda/#/?id=%e2%9d%af-missing-ramda-methods

**Comment by selfrefactor** [comment]
I agree that there should be improvement in the documentation. I ran initially comparison of Rambda build against Ramda custom build and that is why I included this information. But that was long time ago and now the difference might be too little. I will remove this information and I will bring it back if my test proves that there some difference is size.

**Comment by selfrefactor** [comment]
I made small script to create output file for Ramda:

```
const R = require('rambda')
const Ramda = require('ramda')
const { interpolate } = require('rambdax')

const allMethodsRamda = Object.keys(Ramda)
const allMethods = Object.keys(R).filter(x => allMethodsRamda.includes(x)).map(x => `export const ${x} = R.${x};`).join('\n')

let template = `
import * as R from 'ramda';

{{allMethods}} 
`

const content = interpolate(template, {allMethods: allMethods})
console.log(content, `content`)
```

Then I put the `content` into `compare-size.js` file and I created rollup config for this file, that anyone can run on `7.5.0` branch with `yarn build:compare-size`.

I see the output size as 85 kB while Rambda build is 62 kB. So there is still a difference between sizes and perhaps I should look why `packagephobia` show so big size as output. I will keep the information, but I want to thank you as you correctly pointed that more information is needed. 

I will keep the issue open until I update the information with numbers and where they came from.

**Comment by selfrefactor** [comment]
I will leave the label and I will also bookmark the issue, but I will close it as for now, there is not much I can do as it require focus time I don't have currently. I will reopen once I have more info.

**Comment by selfrefactor** [comment]
I haven't forgot about this ticket, but as I said before, it will take time to create proper size comparison script. What I will do is to do a quick check if using `R.add` in a project produce different sizes.
