### ISSUE TITLE
FR: Omit with a deep option

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [selfrefactor/rambda#681]
Background for the FR is, that maybe you have a graphql payload with a lot of `__typename` floating around also in nested objects and you want them all to go away and not only on the first level.

**Comment by selfrefactor** [comment]
really nice. It will be a new method and as it is not part of Ramda API, it will be released with Rambdax. I see other idea that might have traction - `R.omitPaths(`a.b,x.y.z,foo`)` which will do something similar to your suggestion, but you have to be explicit in which property paths you want to omit.

UI cannot give you timeline, but I thank you for the idea. I will keep you posted as soon as I have update.

**Comment by selfrefactor** [comment]
I will have to decline your idea. The thing is that this method in TS context will be hard to create. Also, even if it is available, it will require to manually pass the output interface, which is a big deal actually.

I think better solution will be to use TS and `R.pipe` to build the required output where each function inside `R.pipe` removes property path from input interface.
