### ISSUE TITLE
Lint markdown files

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#684]
https://www.npmjs.com/package/markdownlint

**Comment by kevinlu1248** [comment]
Hey @selfrefactor, I'm one of the developers of Sweep. Sorry this didn't work out, it was some rate limiting issue by GitHub that we fixed already so I re-delivered this ticket. Hopefully it works this time around!

**Comment by selfrefactor** [comment]
Thank you for reaching out, but I will not use it at that time, maybe later.

**Comment by kevinlu1248** [comment]
Sounds good thanks for trying it out. Hope you give it another chance soon.
