### ISSUE TITLE
Fix Typescript typos to TypeScript

### ISSUE THREAD

**Issue by iamandrewluca** [selfrefactor/rambda#687]
### Issue
I was reading through README and saw `Typescript` word. The right writing is `TypeScript`
Wanted to push a PR myself, but I see there are 829 instances of `Typescript` across the codebase, most of them are in README files

<img width="431" alt="image" src="https://github.com/selfrefactor/rambda/assets/1881266/9b6699cf-488e-44af-80df-eb38501abee2">

**Comment by selfrefactor** [comment]
agree; will change it and txs for filling the issue.

**Comment by neshvig10** [comment]
I'm willing to  fix this
