### ISSUE TITLE
Wrong type definition for propEq

### ISSUE THREAD

**Issue by ilteoood** [selfrefactor/rambda#688]
### Issue
With Rambda 8.0.0, propEq parameters order has been flipped in order to match the new signature of Ramda.

Unfortunately, the TypeScript definition still presents the old order:
![image](https://github.com/selfrefactor/rambda/assets/6383527/0e298085-d4ac-4f11-9455-7fdc4bd17cc9)

### Rambda version
8.0.0

### Node.js version
18

**Comment by selfrefactor** [comment]
good catch; will release asap

**Comment by selfrefactor** [comment]
fixed with 8.1.0
