### ISSUE TITLE
forEach allows objects, but doesn't provide props in iterate func

### ISSUE THREAD

**Issue by noobiek** [selfrefactor/rambda#69]
Hi,

R.forEach as I see in source is just a proxy to R.map, but returns original data.
So it seems natural to pass Objects to R.forEach (just like R.map). But unfrotunately second argument (prop) is lost in iterate function.

R.map((val,prop) => ...prop is OK here..., {...})
R.forEach((val,prop) => ...prop is undefined here..., {...})

Otherwise R.forEach loops over object's properties just fine.
Is it possible to make prop available inside forEach iterate func?

Thanks!

**Comment by selfrefactor** [comment]
Deployed in the new `1.1.3` version

**Comment by noobiek** [comment]
Thanks!
