### ISSUE TITLE
Adding array reduce functionality

### ISSUE THREAD

**Issue by Fatxx** [selfrefactor/rambda#7]
hello @selfrefactor ,

Are you willing to accept an implementation for `R.reduce()`? Or is it out of scope?

Thank you and keep the good work.

**Comment by selfrefactor** [comment]
Will be implemented before the end of the week. 
Thank you for the good words.

**Comment by Fatxx** [comment]
Could I open a merge request with this?

**Comment by selfrefactor** [comment]
Sure, you can :+1:

**Comment by selfrefactor** [comment]
I check your PR, there are some things to be done, before proceeding to build process and `npm publish`

My edit will curry `initialValue` as now it is not handled. After doing this and write a few more test cases, we are ready to proceed further. I am at work now, so I will do that later today.

**Comment by Fatxx** [comment]
Ok, great! Thank you.

**Comment by selfrefactor** [comment]
Published to NPM and closing the issue.
