### ISSUE TITLE
Create react app project won't build with Rambda dependency

### ISSUE THREAD

**Issue by aztecrex** [selfrefactor/rambda#71]
Trying to build a create-react-app with Rambda dependency and have this error:

```
Failed to minify the code from this file:

 	./node_modules/rambda/dist/rambda.esm.js:3

Read more here: http://bit.ly/2tRViJ9

```

Version is 1.1.3 but also tried 1.1.1 with same result.

**Comment by ghostthrone** [comment]
Hey
i had the same problem.
To solve i moved `./node_modules/rambda/dist/rambda.esm.js` file content into my project, the project struct is something like this `project-name > src > utils > rambda.js` then you can compile. rambda.js file contains whole content of `./node_modules/rambda/dist/rambda.esm.js`

**Comment by selfrefactor** [comment]
So I try it out and I can confirm that I also received the bug with `create-react-app`. My initial attempt was to update `rollup`, but when I do that, I receive `babel` related problems. I will need to spend some time investigating this and I just write this to let everybody know that I didn't forgot about this opened issue.

**Comment by selfrefactor** [comment]
I fix it with replacing `rollup` pipeline with the one of https://github.com/developit/microbundle

Please try update to the newest `rambda` version and the issue should be gone.
