### ISSUE TITLE
Looking for more core contributers/owners for this project

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#713]
It is time this project to have more than one administrator/owner

If you are interested, please let me know and we'll find a way to discuss this.

**Comment by patrickalima98** [comment]
Hi @selfrefactor  I would like to help you to maintain this library!

**Comment by selfrefactor** [comment]
Thanks for your application, but I'd prefer to be someone from the big contributors to this library.

**Comment by patrickalima98** [comment]
Ok, no problem. Thanks

**Comment by ilteoood** [comment]
@selfrefactor before looking for more contributers, you should fix some aspects of the project first.

A few examples:
- Why the package.json refers to a folder (`rambda-scripts`) which is not versioned in the repo?
- Why lots of files are repeated between `src` and `source` folders?
    - What's the difference between `src` and `source`?
- Why a `CONTRIBUTING.md` is missing?

We heavily use rambda in production for both front-end and back-end projects, I would be more than happy to help here.

**Comment by selfrefactor** [comment]
All valid points @ilteoood so I will answer them in details once I have time, but now I am on vacation. I will write on 4th of June.

**Comment by selfrefactor** [comment]
Hi @ilteoood 
Sorry for the delay; these are the answers:


    Why the package.json refers to a folder (rambda-scripts) which is not versioned in the repo?
   - Initially, everything was part of this repo, but one contributor pointed that this is not ideal, as folder structure as well as git history includes files not related to the library. This is when the other repo was created.
    Why lots of files are repeated between src and source folders?
   - Another contributor pointed that it is bad that Rambdax and Rambda share similar files. Manual sync was prone to errors, so that is why `src` and `source` folders exists. Folder `source` includes all files and tests of Rambdax and Rambda, while `src` is created using build script and it includes only Rambda related files. The advantage is that `src` doesn't include any test files.
    Why a CONTRIBUTING.md is missing?
- There was such file, but it became outdated. I created issue to fix this - https://github.com/selfrefactor/rambda/issues/735
