### ISSUE TITLE
Hijack Question for code-complexity: Add cognitive complexity as well

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [selfrefactor/rambda#718]
Sorry for hijacking rambda issues but the issues for the extension is not open as well as discussions is not open.
So I would ask to also add the sonarqube cognitive complexity metric which deviates from cyclomatic complexity

https://github.com/selfrefactor/code-complexity

**Comment by selfrefactor** [comment]
As it is a fork, I didn't notice that repo didn't have issues as option(fixed now).
Created the same issue there and I am closing this one.
we can discuss there the suggestion
