### ISSUE TITLE
Rambda 9 release?

### ISSUE THREAD

**Issue by memark** [selfrefactor/rambda#719]
On NPM there is version 9, in GitHub only 8.6.

<img width="505" alt="image" src="https://github.com/selfrefactor/rambda/assets/318504/8ce987d2-8f1b-4d62-86e4-4c2d59e810b0">

<img width="157" alt="image" src="https://github.com/selfrefactor/rambda/assets/318504/421aeacb-a5fa-483d-8b7f-703ff1291cb8">

Please make a proper release with release notes / breaking changes. Thanks.

**Comment by selfrefactor** [comment]
Txs, I will make sure that upcoming 9.1.0 will have GH release

**Comment by selfrefactor** [comment]
fixed with 9.1.0

**Comment by memark** [comment]
Thanks!
