### ISSUE TITLE
Add `memoizeWith`

### ISSUE THREAD

**Issue by jirutka** [selfrefactor/rambda#736]
Can you please add function [memoizeWith](https://ramdajs.com/docs/#memoizeWith)?

**Comment by selfrefactor** [comment]
I didn't add it on purpose as it is hard to imagine for me how I can use it in the context of `R.pipe/R.compose`. If you provide such example, I'll be happy to add it.

**Comment by jirutka** [comment]
I don’t understand, why do you need to use it in the context of R.pipe/R.compose? It’s a decorator function to add memoization/caching to the decorated function.

**Comment by selfrefactor** [comment]
what I mean is that most of functions in Ramda/Rambda should be used as part of pipe, otherwise these libraries becomes just another Lodash.

**Comment by selfrefactor** [comment]
Also, keeping state is in my opinion shouldn't be implemented in FP library. I hope you do understand.
