### ISSUE TITLE
There is no `zipObj` function

### ISSUE THREAD

**Issue by wind13** [selfrefactor/rambda#74]
I check this in `ramda`, it has [`zipObj`](http://ramda.cn/docs/#zipObj).

**Comment by selfrefactor** [comment]
will do

**Comment by selfrefactor** [comment]
Shipped with the new `1.1.5` version

**Comment by noobiek** [comment]
Hi,
Not working in REPL (function R.zip and R.zipObj not found).

**Comment by selfrefactor** [comment]
REPL is not always updated with every release, but I will update it with the next version.

**Comment by selfrefactor** [comment]
It works now.
