### ISSUE TITLE
Documentation site not working in Safari

### ISSUE THREAD

**Issue by darky** [selfrefactor/rambda#747]
When documentation site opened in Safari, it's just stuck with white screen of death and CPU consumption 100%

**Comment by selfrefactor** [comment]
That sounds bad. I am not on Apply but I will try with Playwright to reproduce.

**Comment by darky** [comment]
Sorry, it's not related to Safari
It's something like geoblock

https://codecov.io/gh/selfrefactor/rambda/branch/master/graph/badge.svg
☝️ loading very long time and in the end 403 forbidden

**Comment by selfrefactor** [comment]
txs for quick response

**Comment by selfrefactor** [comment]
as it is hard to justify custom script for this, I will remove some badges and calculate if there are any badges that take more time to render.
