### ISSUE TITLE
[BUG] ifElse onTrue() only executes on ifCondition() === true

### ISSUE THREAD

**Issue by mmikeyy** [selfrefactor/rambda#750]
const value = 34;

R.ifElse(
  R.identity as (val: any) => boolean, 
  R.always('true'),
  R.always('false')
)(value)

I would definitely expect this to return 'true'. It returns 'false'. With Ramda, we get the expected 'true'. Unless I missed something, this difference is not documented. But instead of documenting it, I think it should be fixed!

**Comment by selfrefactor** [comment]
Thanks for spotting this. Indeed, boolean transformation was missing, i.e. expected result was boolean but this is too strict.

I will make a release tomorrow, so the fix will be applied in the new version.

**Comment by selfrefactor** [comment]
Released with newest version
