### ISSUE TITLE
typing problem with groupBy

### ISSUE THREAD

**Issue by mmikeyy** [selfrefactor/rambda#752]
Hi again,

Thanks for the recent updates. After updating to the latest version (9.4), my IDE started highlighting a slew of perfectly valid statements that had posed no problems until now. My angular project no longer compiles and I have to adjust the typing in many places. This is a waste of time, especially in cases where the statement is so unambiguously valid.

Here's an example that I simplified to the extreme for the purpose of demonstrating the problem:

```
interface Item {a: string; b: number}
const array: Item[] = [
  {a: 'aa', b: 22},
  {a: 'bb', b: 23},
  {a: 'aaa', b: 222}
]
let result: {[a:string]: Item[]} = {} ;

result = R.groupBy(R.prop('a') as (a: Item) => string, array)

console.log(result)

```
The above executes flawlessly in an environment that doesn't pay attention to typing errors. 

The 'result = ' assignment is however highlighted with the following error:

Type 'Partial>' is not assignable to type '{ [a: string]: Item[]; }'.
  'string' index signatures are incompatible.
    Type 'Item[] | undefined' is not assignable to type 'Item[]'.
      Type 'undefined' is not assignable to type 'Item[]'.
      
which can be avoided by changing the type of 'result' to   {[a:string]: Item[] | undefined}

The problem is that it should be impossible for the groupBy function to produce an 'undefined' value for a key as a key exists only if at least one value was found for that key.

Am I missing something or is there a problem with the typing and it should be corrected?

**Comment by selfrefactor** [comment]
Sorry, but I am closing this issue. My latest change sync TS typings of method with Ramda.

Your example fails for both libraries:

![image](https://github.com/user-attachments/assets/3cf727a8-0751-428d-b515-2313e11c249e)

**Comment by mmikeyy** [comment]
ok... but my point wasn't that Ramda was doing a better job in this particular instance. On the contrary, Rambda used to work where Ramda was failing. Now they both fail, needing code to be cluttered with typing information to account for the possibility of a result that is obviously impossible in the first place. As I said, groupBy cannot produce a result with an undefined value for a key, as if the key exists in the result, it's because groupBy found an object that it derived the key from. So that object is necessarily not undefined.

It's a bit ridiculous (for both libraries) that this:

```
type Item = {a: string};
const list: Item[] = [{a: '1'}, {a: '2'}];
let b: {[index: string]: Item[]};
b = R.groupBy(R.prop('a'), list)
```
is perfectly valid but won't compile because 'Type 'undefined' is not assignable to type 'Item[]'.'

so one now needs to let typescript know that the impossible won't happen as follows:

`b = R.groupBy(R.prop('a'), list) as {[index: string]: Item[]}`

Anyway, I don't want to make this the hill I'll die on. At least Ramda is not doing better here...

**Comment by selfrefactor** [comment]
Thanks for understanding.
I keep eye on changes in Ramda so once they apply a fix to R.groupBy, I will follow.
