### ISSUE TITLE
No `R.min` and `R.max` function

### ISSUE THREAD

**Issue by wind13** [selfrefactor/rambda#76]
There is no `R.min`, `R.minBy` and `R.max`,  `R.max` function which is useful when using `R.reduce`.

- [min](https://ramdajs.com/docs/#min)
- [minBy](https://ramdajs.com/docs/#minBy)

- [max](https://ramdajs.com/docs/#max)
- [maxBy](https://ramdajs.com/docs/#maxBy)

**Comment by selfrefactor** [comment]
Will land in next version

**Comment by JFranciscoRader** [comment]
Also R.nth :sweat_smile: 
BTW this lib is awesome, thanks.

**Comment by selfrefactor** [comment]
Thank you for the nice words- one shouldn't do it for the applause, but how human is to like them; so it is appreciated and I won't forget for `R.nth` which is very spot on suggestion.

**Comment by selfrefactor** [comment]
Thank you for the nice words- one shouldn't do it for the applause, but how human is to like them; so it is appreciated and I won't forget for `R.nth` which is very spot on suggestion.

**Comment by selfrefactor** [comment]
Thank you for the nice words- one shouldn't do it for the applause, but how human is to like them; so it is appreciated and I won't forget for `R.nth` which is very spot on suggestion.

**Comment by selfrefactor** [comment]
All methods are implemented in the latest version.
