### ISSUE TITLE
equals doesn't compare Date objects correctly

### ISSUE THREAD

**Issue by soetji** [selfrefactor/rambda#79]
`R.equals(
  new Date('1/1/2017'),
  new Date('1/1/2018')
) // => true`

**Comment by selfrefactor** [comment]
Nice catch, but on first glance I don't see a lightweight solution to this.

**Comment by sectsect** [comment]
@soetji 
Try the following.
```js
R.equals( new Date('1/1/2017').getTime(), new Date('1/1/2018').getTime() )
```
