### ISSUE TITLE
Provide public ES modules 

### ISSUE THREAD

**Issue by bisubus** [selfrefactor/rambda#80]
`/es` package entry point is conventional in modern libraries.

The suggestion is to provide `rambda/es` imports in _ES5_ and _ES module format_ , [similarly to how it was done  with `ramda/es`](https://unpkg.com/ramda@0.25.0/es/). Notice that Ramda modules are transpiled to ES5 to skip transpilation on bundling, and there is index reimporting file.

The package has `rambda/lib` which is CJS. It doesn't have index (there will be problems with tree-shaking any way) and requires to use module interop when imported as ES modules, this results in increased footprint.

**Comment by selfrefactor** [comment]
I will close this one as there is the same issue [here](https://github.com/selfrefactor/rambdax/issues/21)
