### ISSUE TITLE
Missing typings

### ISSUE THREAD

**Issue by tdecker91** [selfrefactor/rambda#81]
There's still a few missing typings in `index.d.ts`. The following methods are contained in the docs here https://selfrefactor.github.io/rambda/#/  but don't have typings.
```
groupBy
indexBy
indexOf
lastIndexOf
```

Changes I'd like to introduce https://github.com/selfrefactor/rambda/pull/82

**Comment by selfrefactor** [comment]
Thanks for the PR. I accepted it and the changes will apply to the next version.
