### ISSUE TITLE
Typings: omit() return type is the same as the input type

### ISSUE THREAD

**Issue by laurence-myers** [selfrefactor/rambda#83]
Here are the existing types:
```
    omit<T>(names: string[] | string, obj: T): T
    omit(names: string[] | string): <T>(obj: T) => T
```
This means the type of the output value is the same as the type of the input value, but "omit" is removing properties from the object.

These should be more like:
```
    type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
    omit<T, K extends Array<keyof T>>(names: K, obj: T): Omit<T, K[number]>; // both args, string array
    omit<T, K extends keyof T>(name: K, obj: T): Omit<T, K>; // both args, single string
    omit<T, K extends Array<keyof T>>(names: K): (obj: T) => Omit<T, K[number]>; // 1 arg, string array
    omit<T, K extends keyof T>(name: K): (obj: T) => Omit<T, K>; // 1 arg, single string
```

**Comment by selfrefactor** [comment]
You are right about that. Thanks for filling this issue and for suggesting the solution. It will be updated today with new version release.

**Comment by selfrefactor** [comment]
OK, so this works:

```
const a:B  = omit('a',{a:1,b:2})
```

and it gives me correct warning if I do:

```
const a:B  = omit('a',{b:2})
// Argument of type '"a"' is not assignable to parameter of type '"b"'.
```
What I am asking if you can fix the example from the previous comment.

**Comment by laurence-myers** [comment]
Thanks very much for the quick change! :grin: 

Regarding your first example, the type parameters might be confusing. You would expect the second type parameter to be the return type, but that return type is actually automatically inferred using the "Omit" type. Instead, the second type parameter is (a union of) the property names to omit. So, a working example is:

```typescript
const a: B = omit<A, 'a'>('a' ,{ a: 1, b: 2 });
const c: {}  = omit<A, 'a' | 'b'>(['a', 'b'], { a: 1, b: 2 });
```

(There might be a way to write the type definitions without the second type parameter, but I haven't been able to work out how yet.)

**Comment by selfrefactor** [comment]
That is great. I will create examples with Typescript usage of `Rambda` and I will start with your example. I will also refer to you as source of `omit` typings and `omit` examples. I will close the issue, but feel free to comment, if you feel like it.
