### ISSUE TITLE
0's in second array passed into zip causes incorrect result

### ISSUE THREAD

**Issue by ywchan2005** [selfrefactor/rambda#86]
while calling ```zip```, if ```0``` is present in the second array, it causes the resulting array to ignore elements in first array with positions corresponding to those ```0```'s.

for example
```
const result = R.zip(['a', 'b', 'c'], [1, 0, 2])
// => [['a', 1], ['c', 2]]
```
the expected result should be
```
[['a', 1], ['b', 0], ['c', 2]]
```

[sample code](https://rambda.now.sh/?const%20result%20=%20R.zip([%27a%27,%20%27b%27,%20%27c%27],%20[1,%200,%202]))

**Comment by selfrefactor** [comment]
It is weird bug and I want to thank you for the nice big catch. I will look into it and get back to you.

**Comment by selfrefactor** [comment]
As with the previous bug, this method is also not added by me and as it depends on `R.addIndex` I have to remove it as well. I will keep this issue open till the next version is published, so you can commend if you are willing to solve `R.addIndex` and thus actually fixing these 2 bugs.

What I am doing is not best practice, I admit that, but the aim for this library is to reproduce `Ramda` methods with simple code if possible. If not possible, white flag is not far away.

**Comment by selfrefactor** [comment]
I will actually close this issue, but feel free to comment despite that.
