### ISSUE TITLE
Webpack Uglify won't run on module as it is compiled as es6

### ISSUE THREAD

**Issue by jpgorman** [selfrefactor/rambda#9]
Currently this module can't be used in production with webpack as it is es6 and isn't supported by the webpack uglify module.

Can you compile the package to es5 first with either babel or something else, before building with webpack.

**Comment by selfrefactor** [comment]
Nice catch! Yes, I will do that.

**Comment by selfrefactor** [comment]
A clarification is needed - which file you need compiled - `index.js` or `webVersion.js` ?

**Comment by jeanpaulgorman** [comment]
It's the compiled node file - index.js

**Comment by selfrefactor** [comment]
Version 0.7.3 should be now `es2015` compatible. Please let me know if `Uglify` still doesn't work.

**Comment by jeanpaulgorman** [comment]
Fantastic, I'll give it a try :)

**Comment by selfrefactor** [comment]
I am closing the issue, assuming that it works.

**Comment by jpgorman** [comment]
Just tried it today (I've been away). Works a treat, thanks :) 👍
