### ISSUE TITLE
add R.evolve

### ISSUE THREAD

**Issue by the-dr-lazy** [selfrefactor/rambda#91]
Hi

I found Rambda as a good alternative to Ramda. How would be to implement the useful function called `R.evolve`?

**Comment by selfrefactor** [comment]
It was implemented in the extended version of Rambda, which is **Rambdax**. When **Rambdax** hit major version change, I took the chance to deprecate some methods and R.evolve was one of them. But the code is there and it is very easy to be restored. Still, I'd prefer to have this method in Rambdax, not here if that is fine with you. 

I am sending the link to the code:

https://github.com/selfrefactor/rambdax/blob/master/files/deprecated/evolve.js

and spec

https://github.com/selfrefactor/rambdax/blob/master/files/deprecated/evolve.spec.js
