### ISSUE TITLE
Move to typescript

### ISSUE THREAD

**Issue by thebrodmann** [selfrefactor/rambda#92]
Actually, there is an important enhancement at #62, internal support for type definitions is the topmost benefit over Ramda.

I think there can be good contributions from other guys. So having an open issue and a work branch is the most important moves for this big change.

**Comment by selfrefactor** [comment]
I agree, let us leave the issue open for reference. Just pasting the link to the related Typescript issue we are waiting on: https://github.com/Microsoft/TypeScript/issues/5453

**Comment by selfrefactor** [comment]
Sorry @thebrodmann but I will close the issue as at the speed of resolving the Typescipt issue, the feature might not arrive this year. Also, having 1 unresolved issue is like having a clean house with a dirty door.
