### ISSUE TITLE
`map` TypeScript typings

### ISSUE THREAD

**Issue by victordidenko** [selfrefactor/rambda#98]
Either something wrong with `map` typings, or I'm doing something wrong...

```typescript
const splitAndMap = pipe(
  defaultTo(''),
  split(','),
  map(s => `Hi, ${s}!`),
);
```
causes on `map`:
```
Argument of type 'MapInterface<{}>' is not assignable to parameter of type '(x: string[]) => Dictionary<{}>'.
  Type '{}[]' is not assignable to type 'Dictionary<{}>'.
    Index signature is missing in type '{}[]'.ts(2345)
```

**Comment by selfrefactor** [comment]
I can test it on next week as I don't have currently access to my VSCode. My guess is that the problem is the typings of `pipe`, which are inherited from Ramda typings.

My impression is that it is hard to use Typescript with `pipe` or `compose` in both Ramda and Rambda. My solution was to just stop writing such functions as I get tired of passing `any` every other time.

Once Typescript provide variadic function arguments, then Rambda will be rewritten with Typescript. This will allow the final library typings will be generated by Typescipt instead of manually written.

**Comment by selfrefactor** [comment]
One way to make it work is writing similar pseudocode:

```
const splitAndMap = pipe<string, string, string[], string>(
  defaultTo(''),
  split(','),
  map(s => `Hi, ${s}!`),
);
```

as if you read the typings of `R.pipe`, you will see that you actually need to pass the typings of the inner functions(the functions inside `R.pipe`) as Typescript can always deduct these types correctly.

**Comment by victordidenko** [comment]
My guess was that `map` can work with arrays and objects both, and TypeScript unable to choose right definition.

**Comment by selfrefactor** [comment]
That is also very probable. I will post update as soon as I get my hand on my workstation.

**Comment by victordidenko** [comment]
`pipe` is definitely beyond suspicion here. This code
```typescript
const fn = s => parseInt(s, 10);
const result = map(fn)(['1', '2', '3']);
```
complains on each array item `Type 'string' is not assignable to type 'number'`.

As far as I understand following definitions
```typescript
map<In, Out>(fn: MapFunction<In, Out>): MapInterface<Out>

interface MapInterface<T> {
  (list: T[]): T[]
  (obj: Dictionary<T>): Dictionary<T>
}
```
it implies, that map's list argument must have same type, as output list...

**Comment by JaminFarr** [comment]
Yes, it's missing different input output types.

This works.
```ts
map<In, Out>(fn: MapFunction<In, Out>): MapInterface<In, Out>

interface MapInterface<In, Out> {
  (list: In[]): Out[]
  (obj: Dictionary<In>): Dictionary<Out>
}
```

I've created fix PR https://github.com/selfrefactor/rambda/pull/113

**Comment by victordidenko** [comment]
I've tried a bit more, and these looks like two unrelated issues.

`filter` has similar definitions, and also able to work with arrays and dictionaries. And `filter` in `pipe` causes same error, as `map`:
```typescript
const splitAndFilter1 = pipe(
  split(','),
  filter((e: string) => e.length > 0),
);

const splitAndFilter2 = pipe<string, string[], string[]>(
  split(','),
  filter((e: string) => e.length > 0),
);
```
`splitAndFilter2` doesn't show error, while `splitAndFilter1` shows on filter row:
```
Argument of type 'Filter<string>' is not assignable to parameter of type '(x: string[]) => Dictionary<string>'.
  Type 'string[]' is not assignable to type 'Dictionary<string>'.
    Index signature is missing in type 'string[]'
```

**Comment by selfrefactor** [comment]
I thank @JaminFarr for his PR
New version `2.3.2` contains the fix so @victordidenko can test it out and comment on the outcome.

**Comment by victordidenko** [comment]
I tried, new version fixes problem in [this](https://github.com/selfrefactor/rambda/issues/98#issuecomment-467784409) comment (with map output), but [this](https://github.com/selfrefactor/rambda/issues/98#issue-414735633) (topic start) and [this](https://github.com/selfrefactor/rambda/issues/98#issuecomment-468639239) (my previous comment) remains

**Comment by selfrefactor** [comment]
## In relation to the first initial example

We have `pipe<V0, T1, T2, T3>(fn0: (x: V0) => T1, fn1: (x: T1) => T2, fn2: (x: T2) => T3): (x: V0) => T3;`
 declaration.

Which leads to the following:

```
const splitAndMap = pipe<string, string, string[], string[]>(
  defaultTo(''),
  split(','),
  map(s => `Hi, ${s}!`),
);
```

`splitAndMap` is correctly recognized as `string[]`

**Comment by victordidenko** [comment]
Yes, defining types in explicit way solves problem.

I guess, that if `map` and `filter` would work only with arrays, there wouldn't be such problem. TypeScript got confused because these functions can work with arrays and objects both.

So I was wondering, maybe there is a way to write definitions somehow differently, that TypeScript will recognize types without errors, automatically?

Or maybe add two different functions for objects? That will also improve semantics.
But that will break back compatibility.

**Comment by selfrefactor** [comment]
> I guess, that if map and filter would work only with arrays, there wouldn't be such problem. TypeScript got confused because these functions can work with arrays and objects both.

That would be bad decision. These functions are build exactly with this purpose. Typescript definitions are extra and therefore they shouldn't force any change on the actual code. 

> So I was wondering, maybe there is a way to write definitions somehow differently, that TypeScript will recognize types without errors, automatically?

That should happen if Rambda is written in Typscript. At the moment we have to go with what we have.
